### PR TITLE
Update translations for Polish language

### PR DESCRIPTION
**Pull request by jurkian**
Also fixed and added some missing strings from original "root" strings.js

### CODE REVIEW

**Comment by MarcelGerber** [comment]
@jurkian You need to sign the [CLA](http://dev.brackets.io/brackets-contributor-license-agreement.html) first.

@winek Could you maybe do a quick translation review here?

**Comment by abose** [comment]
@jurkian  Thank you for contributing to brackets. 
 You could Join the [brackets discussion forum](https://groups.google.com/forum/#!forum/brackets-dev) to know the latest developments. Brackets community is also reachable on slack at [this link](https://brackets.slack.com/messages/general/details/).

**Comment by jurkian** [comment]
@MarcelGerber I don't want to leave my personal details everywhere. You are free to use my Brackets' commits as you want. Let the Open Source software grow!
@abose Thank you for invitation. I am just starting with GitHub and first of all I have to work on my workflow :)

**Comment by ApfelUser** [comment]
@jurkian That is exactly what the [CLA](http://dev.brackets.io/brackets-contributor-license-agreement.html) is there for. By signing the [CLA](http://dev.brackets.io/brackets-contributor-license-agreement.html) you allow the brackets project to use your code without legal issues for the project.

**Comment by abose** [comment]
@ryanstewart Query about brackets CLA.

**Comment by ficristo** [comment]
I guess this is superseeded by #12028.

**Comment by abose** [comment]
Waiting for confirmation from @jurkian

**Comment by jurkian** [comment]
Sorry for so late answer. @ficristo is right, superseeded as for now. I'm going to sing CLA and prepare up to date translation soon.

**Comment by jurkian** [comment]
I'm closing this Pull Request, it's replaced by more up to date one: https://github.com/adobe/brackets/pull/12372

**Pull request closed without merging**
