### PR TITLE
Fix bug in StringMatch where separator and slash collided

### LINKED ISSUE #10871: Quick Open: Wrong title if underscore in name
1. In `brackets/src/thirdparty`, copy `CodeMirror2` to `CodeMirror2_`
2. Open Brackets, open Quick Open and type `codemirr`

Result:
The first few entries are named `CodeMirrAUTHORS`, `CodeMirrLICENSE` and so on
image

Expected:
The first few entries are named `AUTHORS`, `LICENSE` and so on

cc @peterflynn

### PR DESCRIPTION
**Pull request by marcelgerber**
Fixes #10871.

cc @dangoor

### CODE REVIEW

**Comment by dangoor** [comment]
Looks good to me, and I appreciate that you added a test too. I can't test it at the moment because I, uh, don't have a computer (I'm writing this on an iPad). Should I just merge it or does someone want to test it first?

**Comment by MarcelGerber** [comment]
I'd like to have a second pair of eyes look at those lines so I don't break anything at the end of the Release.
If it takes longer, feel free to merge this in at the beginning of Release 1.4. Thanks!

**Comment by peterflynn** [comment]
Since StringMatch is sort of delicate, I also think it'd be best if someone could take a little time to test before we merge.

**Comment by rroshan1** [comment]
Taking up the task of testing it thoroughly and reviewing.

**Comment by MarcelGerber** [comment]
Could we maybe merge this now that Release 1.4 has just begun so this has a long testing phase?

**Comment by rroshan1** [comment]
@MarcelGerber Changes look good and it fixes the issue it addresses. Scenario testings also went fine.
BUT on running the Jasmine Unit Tests, I see that couple of FindInFiles Integration Tests fail and makes Brackets non-responsive in the process. This is reproducible consistently. Can you please verify if it is introduced due to the changes OR the test case needs to be updated.
NB: Ignore QuickOpen Test failures(issue known and fixed in latest master branch).
We can have this PR merged after the test failures gets addressed.

**Comment by MarcelGerber** [comment]
@rroshan1 That was just an issue of this branch not being merged with latest master.
Now that I merged with master (and rebased), all unit tests pass.

**Comment by rroshan1** [comment]
Cool !!
I am going ahead with the merge then.

**Pull request merged**
