### PR TITLE
Bug Fix for #12111 and #12144

### PR DESCRIPTION
**Pull request by swmitra**
This PR fixes the file close issue.

### CODE REVIEW

**Comment by swmitra** [comment]
ping @ficristo @petetnt @abose Can you guys please confirm the fix using this branch.

**Comment by petetnt** [comment]
Fixes #12111 and #12144.

On related note, why is the `event` variable a global on `src/project/FileViewController.js`? Seems... weird?

**Comment by swmitra** [comment]
@petetnt This "event" handle is from the global context. If the the current execution frame is a result of an event triggered by user or system , this handle is always set at the global context. As the actual event handle is never passed through the call stack , I have used the global handle to verify the context.

**Comment by petetnt** [comment]
Thanks for the explanation @swmitra :+1:

**Comment by abose** [comment]
@swmitra three document integration `integration tests` are failing with this PR.

**Comment by ficristo** [comment]
@abose If you are referring to the `Document Integration` tests they are failing on master too.

@abose @swmitra Are you going to fix all the tests in this PR? Otherwise can you land this? It will be a bit easier to see the other failures.

**Comment by Siphon880gh** [comment]
Hey guys, how do I get this release with the CMD+W bug fix? There hasn't been a release uploaded here:
https://github.com/adobe/brackets/releases

Could I clone it to my computer using git? How do I compile it for Mac afterwards? Thanks.

**Comment by petetnt** [comment]
Hi @Siphon880gh,

there's a guide called [How to hack on Brackets](https://github.com/adobe/brackets/wiki/How-to-Hack-on-Brackets), which takes you through step by step on how to use a development build of Brackets (no building needed, just using `git` and running an single tool).

After you have a dev build running you'll need to merge this branch. For example on `git` commandline:

´``
git fetch upstream swmitra/BugFixesFor1.6
git merge upstream/swmitra/BugFixesFor1.6
```

Restart Brackets and the fix should be applied and working

**Comment by swmitra** [comment]
Re-Targeting to release branch.

**Comment by Siphon880gh** [comment]
Thanks!

**Comment by abose** [comment]
A build refresh is scheduled by his week or next for 1.6and after that the new installers posted will contain this patch.

**Comment by schroef** [comment]
Srry for asking, im kinda a new to this all.. is also see this error with file not closing in the tree list. Im using v1.6 rev1.6.0-16680 on osx 10.11.4

**Comment by n0nag0n** [comment]
I installed this like......3-4 days ago, checked if there was an update (which it says there isn't) and I'm having the same issue. On a Mac, El Capitan with Release 1.6 build 1.6.0-16680 (release 3df0ac6fa) installed.

**Pull request closed without merging**
