### PR TITLE
fits better

### PR DESCRIPTION
**Pull request by JayceeMinecraft**
who agrees?

### CODE REVIEW

**Comment by redmunds** [comment]
@larz0 What do you think? Take this change in core Brackets, or should @JayceeMinecraft create a Theme for it?

**Comment by sbruchmann** [comment]
I just leave this here: [Design Tip: Never Use Black](http://ianstormtaylor.com/design-tip-never-use-black/).

**Comment by larz0** [comment]
@redmunds @JayceeMinecraft should create a theme for it. @JayceeMinecraft if you're not sure how to create a theme, fork a theme from http://brackets-themes.github.io and just change the colors.

**Comment by redmunds** [comment]
@JayceeMinecraft Thanks for submitting this contribution, but we've decided not to take it in core Brackets. You can create your own Theme to use it and upload it to the Brackets Extension Registry to share with others. Closing.

**Pull request closed without merging**
