### PR TITLE
Added will-change property

### PR DESCRIPTION
**Pull request by febLey**

### CODE REVIEW

**Comment by zaggino** [comment]
@febLey you need to sign the http://dev.brackets.io/brackets-contributor-license-agreement.html

**Review by petetnt — APPROVED** [review]
LGTM: ref: https://developer.mozilla.org/en/docs/Web/CSS/will-change

Needs CLA before merge

**Review by zaggino — APPROVED** [review]

**Comment by febLey** [comment]
Do i really need to enter my whole address for the CLA? What will happen with those informations? Where are they stored?

**Comment by zaggino** [comment]
@febLey seriously, nobody's going to verify the details that you put in

**Comment by ficristo** [comment]
@bethomas @nethip can you answer?

**Comment by ficristo** [comment]
I'll land this in #12982.
I think it is a shame nobody answered.

**Pull request closed without merging**
