### PR TITLE
Revert "Fix horizontal scrolling of code hints"

### PR DESCRIPTION
**Pull request by sprintr**
Reverts adobe/brackets#11195

### CODE REVIEW

**Comment by sprintr** [comment]
@abose @MarcelGerber This should get reverted. We don't need it now.

**Comment by abose** [comment]
@MarcelGerber please review this and merge if required.

**Comment by MarcelGerber** [comment]
I don't really know... couldn't this be useful for other Code Hint extensions (yet to come)? Or, OTOH, does it change the layout of any Code Hint extension out there (Ternific, for example)?

**Comment by abose** [comment]
Probably it would be good to revert this back that. that would make it pretty close to the old styles except for the `min-width` prop. reverting.

**Pull request merged**
