### PR TITLE
Add Droid Sans Mono for rendering Unicode (Greek, Cyrillic)

### PR DESCRIPTION
**Pull request by marcelgerber**
Including this font will make #3465 way better.

Why I chose Droid Sans Mono:
- One of the most widely used Google Fonts [> 26,000,000 views this week](https://www.google.com/fonts/specimen/Droid+Sans+Mono#stats)
- Supports pretty much all Unicode characters
- Looks good
- Same size `SourceCodePro-Medium` has (from what I can tell)
- It's a monospace font
- Licensed under Apache License 2.0 (hope it's compatible with MIT; I'm not a license expert)

[Google Fonts page](https://www.google.com/fonts/specimen/Droid+Sans+Mono), [Typecast Demo](http://typecast.com/preview/google/Droid%20Sans%20Mono)

**Screenshots:**
With Greek text, mixed with normal HTML:
image
(Demo text: `Ατ σιθ σαυσαε φοσιβυς τινσιδυνθ, πρι ιν μαγνα θεμπορ δετερρυισεθ. Ιν κυι κυανδο ωμιτθαμ, εα μεα θαμκυαμ εφφισιενδι. Ειυς κυανδο κυαεκυε ιδ εσθ, σωνσυλ απειριαν δυο ιδ. Φελ φοσεντ κυαερενδυμ αδ. Νονυμες ρεπρεχενδυντ ει μεα.`)

With Cyrillic text, mixed with normal HTML:
image
(Demo text: `Ючю амэт долорэж эи, экз дикунт мэнандря трактатоз кюм. Экз жят доминг маиорюм. Мюнырэ жямиляквюы эффякиантур векж йн. Ед орнатюс ныкэжчятатябюз векж, ыам ты одео факёльиси адолэжкэнс. Шапэрэт позтюлант векж но.`)

As better support for Greek/Cyrillic text is often-requested, I think this is a good undertaking.

### CODE REVIEW

**Comment by abose** [comment]
The font would come into play only if `source-sans-pro` doesn't have gliffs for the particular unicode text right?

**Comment by abose** [comment]
I think we should consider Greek,Crillic font issue this release as we have seen a lot of issues in this area; and considering the fact that we have a substantial user base from russia. marking this for 1.4.

**Comment by MarcelGerber** [comment]
Yep, all latin text is still displayed with SourceCodePro.

This would go well together with #8985, which improves Greek/Cyrillic support for the non-editor UI. Maybe we can mark it 1.4, too?

**Comment by abose** [comment]
These two could go independently; but Lets target that too for completeness :+1:

**Comment by abose** [comment]
Update on this: Adobe's type team has informed me that they are extending source code pro to include  Greek/Cyrillic support as required by brackets. 
@MarcelGerber Do you find any other issues that need to be addressed in `source code pro` ?

**Comment by abose** [comment]
https://github.com/adobe-fonts/source-code-pro/issues/48#issuecomment-66559989

**Comment by MarcelGerber** [comment]
Is there any ETA on the release?

I really don't know whether we need other character sets as well. There are obviously many characters Source Code Pro doesn't support (I haven't specifically looked for them, but probably Arabic, Hebrew, Persian, ...), but I don't know how bad they look without font support.

**Comment by abose** [comment]
I had a discussion with the fonts group at adobe and this is what i got from them:
1. brackets font set has MS Gothic (a Japanese font) in both its localized and English name forms in our fallback set – but MS Gothic is not available for bundling, so we’re counting on it being present on the local device.
The fonts team suggested integrating  the Source Han Sans family . Like Source Sans it’s targeted at on-screen text, and would harmonize well with Source Code and remove this dependency on local fonts. Unlike MS Gothic, it could provide support for not only Japanese but also Korean and both forms of Chinese. We are in discussion to get these fonts too "

2. reg source code pro: "The Greek & Cyrillic extensions are in beta condition, and we think it would be ideal for Brackets to incorporate these, give us any feedback you may have, and swap in the final versions when the fonts reach GM."

3.Also they said this
the open source version of Droid Sans Mono only includes a basic Latin character set. The expanded character set which include Cyrillic and Greek (Droid Sans Mono WGL, http://www.fonts.com/font/ascender/droid-sans-mono) is only available as a commercial license -- and therefore cannot be bundled in Adobe software, and certainly not in open source software.

**Comment by MarcelGerber** [comment]
That sounds great! I didn't know fonts had beta phases... The more you know :smile: 

Regarding `MS Gothic/ＭＳ ゴシック`, though:
That's the font that currently renders our Cyrillic/Greek text, but it has big letter spacing and is by no means monospace (see [this screenshot](https://camo.githubusercontent.com/182f565f0ab0020d6a32f5f193e768a5faec9129/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f3130373434372f3339303332312f35346431656665302d613733632d313165322d383063322d3766346563393332306361622e706e67)).

That thing about Droid Sans Mono is strange. I got my copy - with Cyrillic/Greek support - from https://www.google.com/fonts/specimen/Droid+Sans+Mono, where they explicitly state it's under the Apache License 2.0.

**Comment by abose** [comment]
:) i too saw the apache license thing;. I'll keep this thread updated.

**Comment by abose** [comment]
@MarcelGerber I have added the latest fonts in this PR #11301 .

**Comment by MarcelGerber** [comment]
Closing in favor of #11301.

**Pull request closed without merging**
