### PR TITLE
Fix for #11763

### PR DESCRIPTION
**Pull request by manoharprabhu**
The new created file cannot be renamed/showed in file tree/showed in
explorer with no messages if it isn't saved.

The file is checked if it is an InMemoryFile before attempting to perform
the above mentioned operations on it. If it is indeed not saved, then a
message is shown to the user to save the document to proceed. Upon
clicking 'Ok', the save dialog box opens up allowing the user to save the
file.

### CODE REVIEW

**Comment by abose** [comment]
tagging @petetnt

**Comment by petetnt** [comment]
The fix itself LGTM :+1: Not sure if `Rename file` should focus on the file after saving (it's a bit redundant so I think not). 

The phrasing of the error message is a bit harder though like @manoharprabhu you mention in https://github.com/adobe/brackets/issues/11763#issuecomment-152085268.

I might go for something like

> **The file needs to be saved before continuing**
> You'll be prompted to save this file.
> [ OK ]

Could you add an unit test for this @manoharprabhu? Otherwise nice work :100:

**Comment by busykai** [comment]
Wouldn't a better solution be disabling the context menu item if the file is not yet saved? The rename action should not be permitted in the first place. (Instead of permitting it and then showing an error -- it's disruptive.)

**Comment by petetnt** [comment]
@busykai I was thinking about that too (especially with the `rename` in mind). When I was testing this out (I didn't even know that you could create a new file without creating it to the tree before this issue!) I noticed  that it's not exactly obvious what separated *that* file from the others. So in that sense prompting for save did make sense for in-memory files and the disabled options *could* be confusing.  

Then again, those options don't make much sense for files that aren't saved, so in that regard you are absolutely correct @busykai

**Comment by manoharprabhu** [comment]
That sounds reasonable. So is it fine to disable those 3 items in context menu for unsaved files?

**Comment by abose** [comment]
+1 for disabling

**Comment by manoharprabhu** [comment]
Do I have to implement this as an extension?
I can see a extensions like 'CloseOthers' manipulating the context menu.
I found out that I have to listen to the 'beforeContextMenuOpen' event on the WORKING_SET_CONTEXT_MENU and PROJECT_MENU to disable the three items if the file has not been saved yet.

**Comment by abose** [comment]
As this is one of the core workflows, i am inclined to do the change directly in core than in an extension.

**Comment by manoharprabhu** [comment]
@abose , I have registered the event handlers in DefaultMenus.js file. I also had to import the MainViewManager and CommandManager modules to make the change work.
Is there a better place to register the event handlers for disabling the menu items?

**Comment by abose** [comment]
DefaultMenus.js looks fine to make the change.

**Comment by manoharprabhu** [comment]
Hey @abose . I was quite busy over the past couple of weeks. The latest pull request contains required the changes to disable the context menu items for  unsaved files.
I am getting around to writing unit tests for these.

**Pull request closed without merging**
