### PR TITLE
String change for "Next/Previous document" in list order

### PR DESCRIPTION
**Pull request by marcelgerber**
We could also try to make the difference between "Next document" and "Next document in list" more obvious.

### CODE REVIEW

**Comment by mackenza** [comment]
I really think the `Next/Previous document` belongs on this feature and that MRU feature can use `Next/Previous recent document`

**Comment by MarcelGerber** [comment]
@ryanstewart Any feedback on this?

**Comment by ryanstewart** [comment]
Yeah, I think this looks fine. Sorry about the delay!

**Comment by MarcelGerber** [comment]
Merging now (Ryan approved the version I have here via Slack, too).

**Pull request merged**
