### PR TITLE
Update strings.js for HR(croatian)

### PR DESCRIPTION
**Pull request by diomed**
updates for Croatian language

### CODE REVIEW

**Comment by nethip** [comment]
Change the title to reflect the what this PR actually does.

@diomed Could you add some one you could do a linguistic review of this PR?

**Comment by diomed** [comment]
no, I don't know anyone personally who uses github. and I believe there were no complaints to my translation yet. I am "official" translator for this. Did most of it on my own. What I don't know I leave it in english, and what I do  I translate it correctly, in the spirit of my language, so everyone could understand.

**Comment by prksingh** [comment]
Merging.

**Comment by peterflynn** [comment]
@diomed Just fyi, normally we ask for _everything_ to be reviewed by at least one other person -- please don't take it as doubts about your translating abilities, or anything.  You'll see in most other translation pull requests, we try to find a second native speaker to review.  If we can't find one, we may use Google Translate to just do a basic check for typos, etc... but we much prefer a real native speaker to review whenever possible.

**Pull request merged**
