### PR TITLE
Brackets on-demand build trigger

### PR DESCRIPTION
**Pull request by swmitra**
This PR includes build trigger for brackets using which committers can request for a pre-release build on-demand to be posted under brackets releases without manual intervention of Adobe team. 

Once this procedure is tested and known to be working, committers will be notified regarding the new scheme.

### CODE REVIEW

**Comment by ficristo** [comment]
I always assumed eventual changes to brackets-shell will be included in the prerelease.
So, is it the case?

**Comment by swmitra** [comment]
@ficristo For now this is just a test to trigger a build when someone modifies this newly added file. Once that build is triggered, eventually brackets-shell will also be built as we have have to prepare the Adobe signed installer. This means that if we do a shell change and need to build a new installer, we can do the same by just updating this json file in brackets repo. 

But if you are looking for a different capability, please let me know so that we can discuss and include the same in the scheme of things. 

I am restoring the branch @ficristo, as I have to do the build test with this branch for now 😄

**Comment by ficristo** [comment]
I just wanted to be sure that changes to brackets-shell will be picked by this tool, no other capabilities.

> I am restoring the branch

I'm sorry, I thought it wasn't needed anymore.

**Comment by zaggino** [comment]
@swmitra does this work? How do I trigger pre-release builds and where they can be found afterwards?
Please see https://github.com/adobe/brackets/issues/13157

**Comment by swmitra** [comment]
@zaggino We just tested this feature today, and if everything goes as per plan, we will have this live tomorrow 👍 

As I have mentioned, once we are live, I will let all committers know about the steps to trigger a build. Once a build is successful, it will be posted under brackets releases section with the parameters (version, title and description) specified under the newly created 'build.json' file. 
 
I will let you trigger the first build once we are done 😄

**Pull request merged**
