### PR TITLE
Code folding unit tests

### PR DESCRIPTION
**Pull request by thehogfather**
Ref: #10893 
Some simple tests for code-folding. Specifically it tests the following:
1. Gutter fold marks are rendered on startup
2. Folding code creates a folded region in editor
3. Expanding code clears the folded region in editor 
4. Clearing the text marker on folded region expands it and updates the fold gutter 
5. Folded lines have a folded (i.e., closed) marker in the gutter
6. Foldable lines have a foldable (i.e., open) marker in the gutter
7. Persistence of fold states work as expected - i.e., fold states are saved and restored when persistence is enabled
8. Persistence of fold states can be disabled
9. Minimum fold size is obeyed
10. Code folding can be disabled
11. Selecting text does not trigger fold marks when `makeSelectionsFoldable' is disabled
12. Selecting text triggers fold marks when `makeSelectionsFoldable' is enabled
13. Successively selecting text only triggers fold region for the last selection

### CODE REVIEW

**Comment by nethip** [comment]
@thehogfather Thanks for this PR! Really appreciate it. @abose @MarcelGerber @sprintr  Would you guys mind taking a look at this PR.

**Comment by abose** [comment]
@thehogfather Sorry , missed this PR for the release.
Could you resolve the merge conflicts?

**Comment by thehogfather** [comment]
done.

**Comment by abose** [comment]
Thanks @thehogfather . 
verified all unit tests passing. Merging.

**Pull request merged**
