### PR TITLE
update codemirror to 5.24.0

### PR DESCRIPTION
**Pull request by zaggino**
contains various TypeScript improvements (among others) that I'd like to see in master since this upgrade is not doable through an extension

cc @ficristo @petetnt @swmitra

### CODE REVIEW

**Review by swmitra — APPROVED** [review]

**Comment by swmitra** [comment]
This upgrade bring quite a few bug fixes accumulated through 22, 23 and 24. I would also like to see use of sticky prop in position. Good upgrade for Brackets 1.9 👍

**Comment by ficristo** [comment]
This breaks a lot of tests. You need to change them to consider the new sticky property.

**Comment by swmitra** [comment]
Yes @ficristo. For now to leverage on the bug fixes and mode optimizations we can just upgrade the CM version, but to actually use the new features we need a complete development cycle which we can't have for Brackets 1.9. Do let us know if you think that this upgrade alone might cause problems.

**Comment by ficristo** [comment]
For what I looked we only need to adjust our tests.
This only mean that before we checked for `{line: x: ch:y}` now we need to check for `{line: x: ch:y, sticky: null}`. We don't use new features.
Hopefully this is the only change for all breaking tests.

**Comment by zaggino** [comment]
I believe I have resolved test issues, can you please re-check guys?

**Review by swmitra — APPROVED** [review]
I am OK with the test changes. This will reduce our work a lot if position object changes again in future.

**Comment by swmitra** [comment]
Restarted the travis build and all checks are successful. Waiting for @ficristo to approve this PR and we can merge then.

**Comment by ficristo** [comment]
There were still some failures on extensions tests.
(There were other failures but probably related to my system)

**Comment by ficristo** [comment]
I just noticed 5.24.2 was released. Better upgrade to it.

**Comment by zaggino** [comment]
Upgraded to `5.24.2`, sadly something is not right with unit testing on my machine. Some tests do randomly pass and fail and then I try to open developer tools to debug, the whole testing window just freezes, quite terrible development experience.

**Comment by swmitra** [comment]
I will also try to see if I can run the tests and figure out any particular issue @zaggino.

**Comment by zaggino** [comment]
thanks, yesterday all integration tests were passing with this PR and now they are randomly failing, drives me mad but i'll give it a try again probably tomorrow

**Comment by zaggino** [comment]
fixed (hopefully all) extension unit tests, @ficristo can you please have a look and let me know which particular tests still fail because of this PR?

**Comment by ficristo** [comment]
It seems there are still some failures with `Extensions \ JavaScript Code Hinting` and `Extensions \ JSQuickEdit`.
NOTE: I reverted 7883b0134b9923418632bf01ad48849aa8c14d2e before testing. See https://github.com/adobe/brackets/issues/13126

**Comment by zaggino** [comment]
@ficristo fixed those tests, also added a fix for #13126 - https://github.com/adobe/brackets/pull/13116/commits/1de6b887c7fcf23dfe4e93e4d8408811ab55c098?w=1

**Review by ficristo — APPROVED** [review]

**Comment by ficristo** [comment]
Thank you for all the effort.

**Pull request merged**
