### PR TITLE
Removed unnecessary prefixed property

### PR DESCRIPTION
**Pull request by AllThingsSmitty**
Changes made to the sample CSS files

### CODE REVIEW

**Comment by AllThingsSmitty** [comment]
Contributor license agreement (CLA) has been signed. 👍🏼

**Comment by abose** [comment]
Thanks @AllThingsSmitty .
Chrome 43+ supports `animation`. as we are on cef 2623[49] this chage is ok to go on win and mac.
unfortunately, Linux versions are still on 1547[29] and does not have full support of the above as specified in the CEF docs.
 Was this tested on the linux builds?

**Comment by AllThingsSmitty** [comment]
@abose I didn't get to testing it on Linux.

**Comment by MarcelGerber** [comment]
@abose Please keep in mind that these are only changes to the `samples` folder, which is never actually rendered inside our shell. So I think this change is fine, and we can totally expect our users to have adopted Chrome/Chromium 43+, Safari 9+ or Opera 30+. What do you think?

cc @ficristo

**Comment by ficristo** [comment]
These projects should be used to test all the available features of Brackets so we should be sure everything works inside the editor too.
So, while I agree that for Live Preview this PR is fine, I was thinking that some feature like `Quick Edit` may not work correctly?

**Comment by MarcelGerber** [comment]
Quick Edit and such features all run on the "JS-side" of Brackets and are thus doing the same on both the current and the Linux shell.

**Comment by ficristo** [comment]
@MarcelGerber you know more than me the internals of Brackets so if it's features aren't affected this PR is fine.

**Comment by MarcelGerber** [comment]
Tested on Linux.
The animation doesn't work, but for another reason :) (Doesn't work on master as well)

I'll put up a fixup PR right away.

**Pull request merged**
