### PR TITLE
Update LESS -> 2.5.1

### PR DESCRIPTION
**Pull request by marcelgerber**
This is a major update of LESS, including breaking changes. So watch out for broken extensions!
# LESS 1.7.5 -> 2.5.1

https://github.com/less/less.js/blob/master/CHANGELOG.md#251

### CODE REVIEW

**Comment by MarcelGerber** [comment]
Updated LESS to 2.2.0

**Comment by MarcelGerber** [comment]
There are only two extensions using less directly:
* [Themes](https://github.com/MiguelCastillo/Brackets-Themes) (`mirror-style/main.js`) @MiguelCastillo 
* [Swatcher](https://github.com/FreaKzero/brackets-swatcher) (`src/SwatchParser.js`) @FreaKzero

**Comment by MiguelCastillo** [comment]
Let's merge it in... I will work through any regressions in Themes.  Thanks for the heads up!

**Comment by MarcelGerber** [comment]
Updated LESS to 2.3.1

**Comment by abose** [comment]
Risky at this stage. Moving to 1.5
@MarcelGerber Will merge this just after release 1.4 . Could target the latest release 2.5.1 ,

**Comment by abose** [comment]
@MarcelGerber @MiguelCastillo Is this safe to merge in at this time.
We are targetting for 1.5 this month or next.

**Comment by MiguelCastillo** [comment]
I am good merging this.  @MarcelGerber can we merge this one?

**Comment by FreaKzero** [comment]
Also from my side (Sorry ... i didnt response to the message in 2014) im good for the merge since im only parsing variables anyways.

**Comment by MarcelGerber** [comment]
Yes, this is ready. Now merging.

**Comment by MarcelGerber** [comment]
@FreaKzero @MiguelCastillo  Bear in mind, though, that the public API has changed.
See [the changes in this PR](https://github.com/adobe/brackets/pull/10240/files) for what needs to be done to make it work with the new LESS version.

**Pull request merged**
