### PR TITLE
updated Dutch Translation

### PR DESCRIPTION
**Pull request by ghost**
I updated the Dutch translation to the latest version of Brackets. Not all translations are of high quallity, but this made it at least easier for others to make a good qullity translation.

### CODE REVIEW

**Comment by svenvNL** [comment]
I merged the mistakes as shown above by @BBosman and restored retranslations to the old once.

**Comment by redmunds** [comment]
@svenvNL This says "Unknown Repository" -- did you delete the branch from your repo?

**Comment by svenvNL** [comment]
@redmunds, I did, is there a way to fix this or should I make an new Pull Request????

**Comment by svenvNL** [comment]
I have recreated the pull request, see https://github.com/adobe/brackets/pull/10584

**Comment by redmunds** [comment]
@svenvNL I don't know of a way to fix this PR, so I'll Close this one and you can create a new one. Also, Release 1.2 is now in the `release` branch, so you should target that branch (i.e. *not* `master`).

**Pull request closed without merging**
