### PR TITLE
Skip template literals when extracting JS functions

### LINKED ISSUE #13036: Quick Edit
Qiuck edit does not display the entire funciton when using template literatles with embed expressions.
```
function hi(name){
    let works `hello ` + name;
    let breaks = `Hello ${name}`; // quick edit ends on this line
    console.log(works); //the rest of the function does not return
    console.log(breaks);
}
```
When using quick edit code is displayed like:
```
function hi(name){
    let works `hello ` + name; 
    let breaks = `Hello ${name}`; // quick edit ends on this line
```

### PR DESCRIPTION
**Pull request by RaymondLim**
This fixes #13036.

### CODE REVIEW

**Comment by swmitra** [comment]
@RaymondLim Is this ready for review? 
The tweak in the token filter looks good to me though 👍

**Review by petetnt — APPROVED** [review]
LGTM

**Comment by RaymondLim** [comment]
@swmitra Yes, it's a simple fix and ready to review.

**Review by swmitra — APPROVED** [review]
LGTM

**Comment by petetnt** [comment]
Thanks @RaymondLim 👍

**Pull request merged**
