### PR TITLE
Bug: 12766 - Now language mode can be changed for unsaved Untitled Do…

### PR DESCRIPTION
**Pull request by saurabh95**
Bug: #12766 - Now language mode can be changed for unsaved Untitled Documents

### CODE REVIEW

**Review by petetnt — COMMENTED** [review]
Codewise LGTM, haven't had time to test this yet

**Comment by ficristo** [comment]
I believe this fixes part of #11637 but not #12766.
If you already didn't you should take a look to the corresponding trello card:
https://trello.com/c/CNXuU4TY/1369-switch-language-type-of-untitled-documents

I defer review to @petetnt and @swmitra on this one.

**Review by swmitra — APPROVED** [review]
Looks good to me.

**Comment by swmitra** [comment]
@petetnt Once you approve, I will merge this PR 😄

**Comment by swmitra** [comment]
Merging this PR. 
@petetnt do let us know if you discover any issues with this. 
I haven't found any issues after using this branch for a couple of days.

**Comment by Grafluxe** [comment]
Thanks for adding this feature, as it is very useful. I found a bug and reported here: [13381](https://github.com/adobe/brackets/issues/13381).

@swmitra

**Pull request merged**
