### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by TylerL-uxai**
Increased usability from a UX design guy. Trying to communicate information

### CODE REVIEW

**Comment by abose** [comment]
Brackets is not a text editer as we see it, it is more of a light wight code editor. So the text is not accurate.

**Comment by sprintr** [comment]
@abose is rights, we have been calling it a Code editor from the day 1.
http://dev.brackets.io/preso/intro/#/4

**Comment by Denisov21** [comment]
@Squ34k3rZ must submitted the contributor license agreement. See http://dev.brackets.io/brackets-contributor-license-agreement.html.

**Comment by Squ34k3rZ** [comment]
Hey guys, that's great. I wonder if you're the same as the people who would be interested in using Brackets, and if text editor is more clear? If not, then use "code editor"! Anything's better than "Welcome to blah blah blah" as your title. Someone make the PR.

**Comment by abose** [comment]
closing as new pr submitted.

**Pull request closed without merging**
