### PR TITLE
Add complementary color for text to be clearly visible

### PR DESCRIPTION
**Pull request by prafulVaishnav**

### CODE REVIEW

**Comment by prafulVaishnav** [comment]
Fix for issue https://github.com/adobe/brackets/issues/10923

**Comment by rroshan1** [comment]
@prafulVaishnav Can you post a screenshot of how it would appear with your fix- either here or in the issue.

**Comment by nethip** [comment]
@prafulVaishnav As mentioned by @njx, you should test it out with other themes like mystique as well.

**Comment by prafulVaishnav** [comment]
@rroshan1 Here is the snapshot.
light-theme

@nethip Preview (marked in red) will remain same for all themes

**Comment by rroshan1** [comment]
Looks good.. Merging it.

**Pull request merged**
