### PR TITLE
Add "replace all" button when doing find and replace

### PR DESCRIPTION
**Pull request by amrelnaggar**
For #11126.

### CODE REVIEW

**Comment by ficristo** [comment]
I didn't look closely at the code but I wonder if changing the button id could break extensions.
That said this needs at least a test.

**Comment by amrelnaggar** [comment]
Sorry I've been pretty busy.

I didn't think about extensions. Would it be better if I kept the button id as it was and made a new id for Replace all button? Or unit tests will be enough?

**Comment by ficristo** [comment]
@amrelnaggar I looked around on the public available extensions and I think this is safe as is. So only the test is needed.

It is only to understand if this is something that would be contributed back from Adobe: @swmitra @madanbn?

**Comment by amrelnaggar** [comment]
I added the test.

**Comment by ficristo** [comment]
@amrelnaggar could you merge master so to resolve the conflicts?

**Comment by amrelnaggar** [comment]
@ficristo All conflicts have been resolved. 

If there is anything else needs to be done just let me know.

**Comment by ficristo** [comment]
Something went wrong. It seems you merged an old version of master.
You can use `git rebase -i ...` to drop the last two commits and then try to run `git fetch upstream` and merge again `upstream/master`
Alternatively you can open a new fresh PR.

**Comment by amrelnaggar** [comment]
@ficristo I created a new PR #12988. 

Closing this PR.

**Pull request closed without merging**
