### PR TITLE
Update CSS property hints

### PR DESCRIPTION
**Pull request by valtlai**
Reordered properties and their values alphabetically.

Added CSS-wide keywords – `inherit`, `initial`, `revert`, `unset` – to the end of arrays.

<details>
<summary>Added properties</summary>

* `backdrop-filter`
* `background-position-x`
* `background-position-y`
* `block-size`
* `border-block-end-color`
* `border-block-end-style`
* `border-block-end-width`
* `border-block-end`
* `border-block-start-color`
* `border-block-start-style`
* `border-block-start-width`
* `border-block-start`
* `border-inline-end-color`
* `border-inline-end-style`
* `border-inline-end-width`
* `border-inline-end`
* `border-inline-start-color`
* `border-inline-start-style`
* `border-inline-start-width`
* `border-inline-start`
* `clip-path`
* `clip-rule`
* `contain`
* `font-variation-settings`
* `image-rendering`
* `inline-size`
* `justify-items`
* `justify-self`
* `margin-block-end`
* `margin-block-start`
* `margin-inline-end`
* `margin-inline-start`
* `max-block-size`
* `max-inline-size`
* `min-block-size`
* `min-inline-size`
* `offset-distance`
* `offset-path`
* `offset-rotate`
* `offset`
* `overflow-anchor`
* `overflow-wrap`
* `overscroll-behavior-x`
* `overscroll-behavior-y`
* `overscroll-behavior`
* `padding-block-end`
* `padding-block-start`
* `padding-inline-end`
* `padding-inline-start`
* `place-content`
* `place-items`
* `place-self`
* `scroll-margin-block-end`
* `scroll-margin-block-start`
* `scroll-margin-block`
* `scroll-margin-bottom`
* `scroll-margin-inline-end`
* `scroll-margin-inline-start`
* `scroll-margin-inline`
* `scroll-margin-left`
* `scroll-margin-right`
* `scroll-margin-top`
* `scroll-margin`
* `scroll-padding-block-end`
* `scroll-padding-block-start`
* `scroll-padding-block`
* `scroll-padding-bottom`
* `scroll-padding-inline-end`
* `scroll-padding-inline-start`
* `scroll-padding-inline`
* `scroll-padding-left`
* `scroll-padding-right`
* `scroll-padding-top`
* `scroll-padding`
* `scroll-snap-align`
* `scroll-snap-stop`
* `scroll-snap-type`
* `speak`
* `text-combine-upright`
* `text-justify`
* `text-orientation`
* `text-size-adjust`
* `touch-action`
* `transform-box`
* `writing-mode`
</details>

<details>
<summary>Updated value lists</summary>

| Property | Added values | Removed values |
| --- | --- | --- |
| `align-content` | `baseline`<br/>`end`<br/>`first`<br/>`last`<br/>`normal`<br/>`safe`<br/>`space-evenly`<br/>`start`<br/>`unsafe`
| `align-items` | `end`<br/>`first`<br/>`last`<br/>`normal`<br/>`safe`<br/>`self-end`<br/>`self-start`<br/>`start`<br/>`unsafe`
| `align-self` | `last`<br/>`normal`<br/>`safe`<br/>`self-end`<br/>`self-start`<br/>`start`<br/>`unsafe`
| `box-shadow` | `inset`
| `clear` | `inline-end`<br/>`inline-start`
| `clip` | `rect()`
| `float` | `inline-end`<br/>`inline-start`
| `image-orientation` | `flip`<br/>`from-image`
| `justify-content` | `end`<br/>`left`<br/>`normal`<br/>`right`<br/>`safe`<br/>`space-evenly`<br/>`start`<br/>`stretch`<br/>`unsafe`
| `text-align` | `end`<br/>`start`
| `text-align-last` | `end`<br/>`start`
| `unicode-bidi` | `isolate`<br/>`isolate-override`<br/>`plaintext`
| `background-image` | `conic-gradient()`<br/>`cross-fade()`<br/>`none`<br/>`repeating-conic-gradient()`
| `break-after`<br/>`break-before` | `recto`<br/>`verso` | `always`
| `height`<br/>`width`<br/>`max-height`<br/>`min-height` | `fit-content`<br/>`max-content`<br/>`min-content`
| `filter` | | `custom()`
| `font-family` | `system-ui`
| `font-synthesis` | `small-caps`
| `min-height`<br/>`min-width` | `auto`<br/>`fit-content`<br/>`max-content`<br/>`min-content`
</details>

<details>
<summary>Removed properties</summary>

(Deprecated, replaced with `break-*`)
* `region-break-after`
* `region-break-before`
* `region-break-inside`.
</details>

### CODE REVIEW

**Review by petetnt — APPROVED** [review]

**Comment by ficristo** [comment]
It seems to me that many rules you are adding aren't implemented by the browser vendors, at least according to https://caniuse.com
I don't know what is the rule at Adobe, but I'm not sure if they are really useful if no one can use them.

@valtlai @petetnt what do you think of not add `inherit, initial, revert, unset` in the configuration, and instead look a way of add them directly in the code? It is easy to mistype or forget them if they are in the config.

Also please take a look at the tests.

**Comment by valtlai** [comment]
@ficristo Yeah, we should add the global values dynamically.

Something like this before any use of `properties` would work:

```js
let globalValues = ["inherit", "initial", "revert", "unset"];

for (let values of Object.values(properties)) {
    values.push(...globalValues);
}
```

**Review by ta-riq — APPROVED** [review]
This is just amazing...

**Comment by nethip** [comment]
@valtlai Great work! Could you site the url (like mozilla webdocs e.t.c.) from which you have updated the hints?

**Comment by ficristo** [comment]
@valtlai for the global values [here](https://github.com/adobe/brackets/blob/53f231827fdff1dc877079c4d0b043357902005d/src/extensions/default/CSSCodeHints/main.js#L312) seems a good place. Could you check?
If it does work for you, could you open a PR with only that (and related tests fixed)?

**Comment by valtlai** [comment]
I’ll close this now and make new, smaller PRs later.

**Pull request closed without merging**
