### PR TITLE
Add menu item for LiveDev MultiBrowser mode

### PR DESCRIPTION
**Pull request by redmunds**
This is for #10239 

cc @busykai

### CODE REVIEW

**Comment by busykai** [comment]
@redmunds, thanks for taking this on. I was waiting for #10285 to get attention since it defines the same preference. Anyway, I'll review and land this and then re-base the other one (quite important, by the way).

**Comment by busykai** [comment]
@redmunds, I think the pref definition should be in `LiveDevelopment/main.js` as well as its handling. Is there any specific reason why we would want it in `Debug` instead of `File` (next to 'Live Preview')? I understand this is experimental still, but the pref and its command handling really belongs to the subsystem itself.

**Comment by sbruchmann** [comment]
We could label the menu item as ‘Enable Live Preview MultiBrowser (Experimental)’.

**Comment by redmunds** [comment]
@busykai I thought this would just be a temporary solution, so that's why I hard-coded the pref id and put it in the Debug menu.

**Comment by busykai** [comment]
@redmunds, i sincerely hoped to land #10285 for 1.2. what if i merge this branch into that PR and re-work. we still don't know for how long both implementations would hang around together (probably for quite a while), so having the option exposed next to launch command in `File` makes more sense to me. what do you think?

**Comment by redmunds** [comment]
@busykai 

> what if i merge this branch into that PR

Sounds good. I'll just close this one.

**Comment by redmunds** [comment]
Closing.

@busykai Let me know when you're done with the **randy/issue-10239** branch so I can delete it.

**Comment by busykai** [comment]
@redmunds, merged and deleted the branch, but #10285 is not yet ready.

**Pull request closed without merging**
