### PR TITLE
do nothing when trying to reset with the same content which is already present

### PR DESCRIPTION
**Pull request by zaggino**
I've encountered a case of https://github.com/adobe/brackets/issues/11826 and this fixes it (don't necessarily fix all possible cases but it is at least something)

cc @nethip @petetnt

### CODE REVIEW

**Comment by ficristo** [comment]
@zaggino it would be awesome if you can add a test case.

**Comment by petetnt** [comment]
Most likely fixes things like zaggino/brackets-git#1274 to some extent. Looks good to me.

**Comment by zaggino** [comment]
@ficristo test added, i've tested that it fails before and passes after the fix too

**Comment by nethip** [comment]
Nice fix @zaggino . LGTM. 

Note: I am going ahead with the merge. Travis is failing because of the API limit issues.

**Comment by nethip** [comment]
Thanks @zaggino

**Comment by ficristo** [comment]
> test added

@zaggino great job, thank you.

**Pull request merged**
