### PR TITLE
pl lang update

### PR DESCRIPTION
**Pull request by karolkrupa**

### CODE REVIEW

**Comment by Denisov21** [comment]
@Exus1 must submitted the contributor license agreement. See http://dev.brackets.io/brackets-contributor-license-agreement.html

Thank @Exus1 for this PR!

**Comment by abose** [comment]
Thanks @Exus1 for the change
tagging @winek @jurkian to review.

**Comment by winek** [comment]
I've added some comments to the diff. Other than that, good job.

**Comment by abose** [comment]
Thanks @winek for reviewing. @Exus1 Can you take a look at the review comments.

**Comment by abose** [comment]
Ping @Exus1

**Comment by abose** [comment]
Closing long pending PR. Please feel free to reopen if you can contribute to this.

**Pull request closed without merging**
