### PR TITLE
Unprefix more CSS

### PR DESCRIPTION
**Pull request by valtlai**
Unprefix
– properties `filter`&nbsp;[🔸](https://caniuse.com/#feat=css-filters), `transform`&nbsp;[🔹](https://caniuse.com/#feat=transforms2d), `animation`&nbsp;[🔹](https://caniuse.com/#feat=css-animation), `background-clip`&nbsp;[🔹](https://caniuse.com/#feat=background-img-opts), `box-sizing`&nbsp;[🔹](https://caniuse.com/#feat=css3-boxsizing), `hyphens`&nbsp;[🔺](https://caniuse.com/#feat=css-hyphens)
– at-rule `@keyframes`&nbsp;[🔹](https://caniuse.com/#feat=css-animation)
– values `max-content` (for `width`)&nbsp;[🔹](https://developer.mozilla.org/en-US/docs/Web/CSS/width#Browser_compatibility), `linear-gradient()`&nbsp;[🔹](https://caniuse.com/#feat=css-gradients)
– media query `min-resolution`&nbsp;[🔹](https://caniuse.com/#feat=css-media-resolution) (was [`-webkit-`]`min-device-pixel-ratio`).

Add prefixless `user-select` (but preserve prefixed versions for now).

Use `:-webkit-any()`&nbsp;[🔹](https://caniuse.com/#feat=css-matches-pseudo) for scrollbar selectors.

Comments are kept (moved after prefixless properties).

[🔹= supported Chromium ≥ 49 without prefix, 🔸= with prefix only, ♦️ = not supported with or without prefix on Chromium 49] Emojis are clickable!

Linux: Chromium 53, Mac & Windows: Chromium 49.

### CODE REVIEW

**Comment by nethip** [comment]
Good job on the PR @valtlai! 👍

**Comment by nethip** [comment]
@valtlai Can you sign the CLA located at http://dev.brackets.io/brackets-contributor-license-agreement.html?

**Comment by valtlai** [comment]
@nethip Done. (Although I have done it before. I have changed my email on Github which could cause this.)

**Review by petetnt — APPROVED** [review]
Changes LGTM

**Comment by nethip** [comment]
Is 53 the min required Chromium version for this PR? If yes, then we should hold on merging this PR as we are on 49 on Win and Mac and 53 on Linux.

**Comment by valtlai** [comment]
Prefixless `filter` is unsupported on Chromium 49. `hyphens` isn’t supported at all on 49, with or without prefix, but that doesn’t change anything.

So I could add prefix back for `filter` and make new PR for it later.

**Comment by valtlai** [comment]
(Added support links and status on the first message.)

Since most of the changes relate to `filter` (which requires prefix before Chromium 35), I would like to wait unless Mac and Windows use at least Chromium 35.

**Comment by valtlai** [comment]
What are the Chromium versions now? Maybe this can be finally merged. 😅

**Comment by valtlai** [comment]
I don’t want to sign the new CLA, so closing.

**Pull request closed without merging**
