### PR TITLE
Indonesian translation updates

### PR DESCRIPTION
**Pull request by resir014**
The following commits contain updates to the Indonesian translation. Fixed some translations, new strings added, and the Getting Started page is also revamped to match the new version.

As always, this translation loosely follows the transliteration guidelines provided here: http://www.vlsm.org/etc/baku-0.txt

### CODE REVIEW

**Comment by nethip** [comment]
@resir014 Could you add some one who can do a linguistic review on this PR?

**Comment by yolapop** [comment]
@nethip Hi, is it okay if I review this translation? (But I'm not a linguist, unfortunately we don't really know any linguist here.. or if you really need a linguist, maybe that should be the requirement upfront)

**Comment by prksingh** [comment]
@yolapop Please go ahead and review. By linguistic review, I think he was expecting a 'language specific' review and not a code review. Don't need a linguist to review this. Thanks

**Comment by resir014** [comment]
@prksingh Okay, @yolapop's already working on it and I'll merge their changes into this PR when we're ready.

**Comment by resir014** [comment]
@nethip @prksingh Okay, our review is done and we've pushed our changes.

**Comment by prksingh** [comment]
@resir014 @yolapop Thanks. Merging.

**Pull request merged**
