### PR TITLE
Latest source code pro with Russian / Cyrillic / Greek support. 

### PR DESCRIPTION
**Pull request by abose**
Latest source code pro with Russian / Cyrillic / Greek support.
these fonts now support the WGL4 character set.

### CODE REVIEW

**Comment by MarcelGerber** [comment]
Note: Look over here to see the changes and compare the old and new versions: https://github.com/adobe/brackets/commit/07c3de7d60cc617974036064f09d98c349875cc4

The new version looks bolder and appears to be more readable to me.
I like it.

**Comment by abose** [comment]
+1 I too like the new look of the fonts.

**Comment by abose** [comment]
@rawat11 If There are no significant defects apart from this, Can we go ahead with this integration ?

**Comment by sprintr** [comment]
After trying this out with my normal preferences (13px, "SourceCodePro-Medium"), I found that superscript dot of letter i doesn't have much distance from its bottom body and seems to be touching each other.

after
before

**Comment by nethip** [comment]
@sprintr Good observation! We should watch out for these kind of changes which are subtle but might impact the readability of code in general. 

@rawat11 Please test specifically on MAC as there seem to be lot of font rendering issues on MAC and I am sure you will find a jewel in there :smile:

**Comment by nethip** [comment]
@sprintr Another question. Are you seeing this with certain font sizes or are you seeing this in general with all the font sizes?

**Comment by sprintr** [comment]
@nethip It happen for (16px, 19px, 21px, 25px, 28px, 42px) etc as well, but seems bearable. with 13px it seems touching.

**Comment by sprintr** [comment]
Using my color palette extension, to get a good view of the problem with i.

2015-06-25 02_25_30-c__users_aminullah_desktop_greenshot_after png test - brackets

**Comment by rawat11** [comment]
@abose Yes, the new font is definitely more readable, our internal team is verifying it, will update once it's done.

**Comment by nethip** [comment]
@sprintr Thanks for the screenshots. @rawat11 do we want to file a bug at https://github.com/adobe-fonts/source-code-pro

**Comment by rawat11** [comment]
@nethip On MAC, there is some issue with the font rendering, some of the characters are not clearly visible with the respect to the other characters on the same plane.
Also there visibility is increased once we increase the font size.



On increasing the font size 

mac


And on windows the same data renders nicely
cyrillic

**Comment by nethip** [comment]
@rawat11 Thanks! Could you go ahead and update [this](https://github.com/adobe-fonts/source-code-pro/issues/98) with the above screenshots.

**Comment by rawat11** [comment]
@nethip We already have a issue raised there, do you want me log another ? I can do that otherwise

**Comment by nethip** [comment]
@rawat11 That's fine! Let us wait to hear from @pauldhunt on that.

**Comment by abose** [comment]
Reverted the font to TTF. Though I like the OTF rendering in windows better, Some of the character glyphs doesn't work well in windows[see https://github.com/adobe-fonts/source-code-pro/issues/98 for discussion].

**Comment by rawat11** [comment]
@nethip The new fonts looks good to the linguist team. We can go ahead with the fonts

**Comment by abose** [comment]
Thanks @rawat11 For the detailed tests. Merging.

**Pull request merged**
