### PR TITLE
Add Dart mode

### PR DESCRIPTION
**Pull request by marcelgerber**
The new CM version (not yet in Brackets) has a Dart mode implemented.
For https://github.com/adobe/brackets/issues/6087.

### CODE REVIEW

**Comment by peterflynn** [comment]
@MarcelGerber Is this mergable before the new CM lands?  It seems like LanguageManager will emit console errors (at the least) since the mode doesn't exist yet.

**Comment by MarcelGerber** [comment]
I haven't tested it, but it's probably best to wait for the CM merge.
I just didn't want to forget this as it was an often-wished feature and it was easy to do.

**Comment by MarcelGerber** [comment]
@peterflynn Time for review now that we have latest CM.

**Comment by peterflynn** [comment]
Cool, looks good!  I find it weird that the mimetype starts with `application/` instead of `text/` like most other CodeMirror modes, but that's how it's defined upstream... so it's not our problem.

**Pull request merged**
