### PR TITLE
UX Fix

### PR DESCRIPTION
**Pull request by TylerL-uxai**
Continued from https://github.com/adobe/brackets/pull/11603#issuecomment-132113561

### CODE REVIEW

**Comment by abose** [comment]
Instead of the text, the logo+brackets text might be better (like the git page for atom). 
tagging @larz0

**Comment by larz0** [comment]
@abose yep you're right :+1:

**Comment by abose** [comment]
@Squ34k3rZ Would you be interested in making that change?

**Comment by Squ34k3rZ** [comment]
Update: Added logo
http://i.imgur.com/7snp2ca.png

**Comment by abose** [comment]
image
Proportions are a bit off. See. https://github.com/atom/atom page for their banner page.

**Comment by abose** [comment]
Also could you use this U?RL for the logo http://blog.brackets.io/wp-content/uploads/2013/04/brackets.png

**Comment by TylerL-uxai** [comment]
@abose Should we add the bigger font to the brackets image? The dimension of this image is 256px tall and the biggest markdown font is 36px. For the two to match, we could add some text to the image or shrink the size of the logo to 36px tall.

**Comment by TylerL-uxai** [comment]
Here's an image that's 20% of the image you linked. It should be close to the right size. I did some experimentation in photoshop to get it.
brackets

**Comment by abose** [comment]
Or the entire logog + text can be composed as an image. Atom's github page does this.

**Comment by Denisov21** [comment]
Good idea @TylerL-uxai for me!

**Comment by ficristo** [comment]
@TylerL-uxai if you are still interested the suggestion of @abose is still valid.
I close this for now.

PS: since you have changed your github username you have to sign again the CLA.

**Pull request closed without merging**
