### PR TITLE
Fixes issue #13227

### LINKED ISSUE #13227: Replace .border-radius mixin with border-radius css in brackets_patterns_override.less
### Description

In `src/styles/brackets_patterns_override.less` there are some mentions of `.border-radius` mixin.
These can safely replaced with the corresponding css `border-radius`.
So `.border-radius(0 0 3px 3px);` will be `border-radius: 0 0 3px 3px;`

There are some other mentions in the tree, but they are in bootstrap files or in files where it is necessary, so there should be left untouched.

### PR DESCRIPTION
**Pull request by parthsharma2**
Replaced .border-radius with border-radius css in brackets_patterns_override.less

This fixes #13227

### CODE REVIEW

**Comment by petetnt** [comment]
Hi @parthsharma2, could you sign the Contributors License Agreement (CLA) http://dev.brackets.io/brackets-contributor-license-agreement.html. The PR itself LGTM!

**Comment by parthsharma2** [comment]
@petetnt, I have signed the Contributors License Agreement. :)

**Review by zaggino — APPROVED** [review]

**Review by petetnt — APPROVED** [review]

**Comment by zaggino** [comment]
Thanks @parthsharma2 !

**Comment by parthsharma2** [comment]
@zaggino I would like to contribute a lot more.😃

**Comment by zaggino** [comment]
@parthsharma2 just pick an issue you think you'd handle and make a PR, we'll definitely be happy to help with a few tips if you get stuck on something

**Pull request merged**
