### PR TITLE
undo history not working, when line-endings change after save

### PR DESCRIPTION
**Pull request by zaggino**
For a bug identified in https://github.com/adobe/brackets/issues/11826#issuecomment-257429242

credits to @vahid-sanati for identifying this, put up a PR so we can have it merged asap

cc @petetnt @ficristo

### CODE REVIEW

**Comment by ficristo** [comment]
The test added in https://github.com/adobe/brackets/pull/12681 probably should be updated or we should add a new one for this case.
It exists a `Document.normalizeText` which normalize line endings: maybe we should update to check also for `\r` and use it, but it doesn't check for `null` text, so maybe not.

Looking at the commits for 1.5 https://github.com/adobe/brackets/compare/release-1.4...release-1.5
there are a couple of upgrade of CodeMirror. In that version of CodeMirror it was changed a bit the way new line endings where used and maybe that broke some assumptions of Brackets.

**Comment by petetnt** [comment]
Would it be worth it to extract and extend `Document.normalizeText` to [FileUtils.js](https://github.com/adobe/brackets/blob/master/src/file/FileUtils.js) with other line ending related methods? Then we could just use `FileUtils.normalizeLineEndings(text)` which would return normalized text or `null`.

The solution for the problem LGTM, just 🚲 🏠

**Comment by zaggino** [comment]
I wanted to use `FileUtils.normalizeLineEndings` but when I included it in the file it lead to circular dependencies and whole Brackets broke 😒 Really hate requirejs

**Comment by zaggino** [comment]
Feel free to push/modify this branch if you want, I have very little time to give to this urgently.

**Comment by petetnt** [comment]
> Really hate requirejs

Ditto. I say lets merge this now and bikeshed the normalization later.

**Comment by ficristo** [comment]
If you want to merge go ahead, but a test is really needed here. At least file a followup for it.

**Comment by zaggino** [comment]
put up a test;

+ i believe that CM is returning always `\n` line-endings after the change @ficristo mentioned but i don't have time to investigate properly

**Comment by ficristo** [comment]
AFAIK if the lineSeparator option is not set CodeMirror return always `\n` line endings.

**Review by ficristo — APPROVED** [review]

**Comment by petetnt** [comment]
Kinda worried about possible performance issues with larger files (possibly leading to `External file changes`-dialogs?) but otherwise LGTM.

**Review by petetnt — APPROVED** [review]

**Review by swmitra — APPROVED** [review]

**Comment by swmitra** [comment]
Merging.

**Comment by swmitra** [comment]
Great work @vahid-sanati @zaggino @ficristo @petetnt

**Pull request merged**
