### PR TITLE
Zaggino/update extension manager deps

### PR DESCRIPTION
**Pull request by zaggino**
Replacement for https://github.com/adobe/brackets/pull/10372 to keep from commiting `node_modules` to git as we should really abandon that practice where possible.

Related https://github.com/adobe/brackets/issues/12898

cc @ficristo 

Note: the webpack approach for semver is taken from brackets-electron, where it's implemented and works well if dependencies (in this case semver) don't provide amd build that we need to use in the browser code

Note2: sorry the diff is quite hard to read because of all the deletes, reading through commits might be easier

### CODE REVIEW

**Comment by ficristo** [comment]
I would prefer if someone more familiar with webpack could take a look.
Maybe someone at Adobe?

**Comment by zaggino** [comment]
@ficristo this is now up to date with master after https://github.com/adobe/brackets/pull/12972 merge. Not sure if anyone from Adobe will have time to look at this anytime soon.

**Comment by ficristo** [comment]
I'm sorry, but I am really not confident in reviewing this.
Maybe @petetnt or @MiguelCastillo can?

**Comment by ficristo** [comment]
`src/extensibility/node` is exported as a zip for the registry (see `brackets-registry/deps`), so it seems to me it needs to be a standalone project or at least we need some way to export the zip: from what I can tell this breaks it.
@zaggino do you know how the zip is created? Or maybe @ingorichter or @redmunds.

**Comment by redmunds** [comment]
I believe that src/extensibility is used by both Brackets and the Brackets Extension Registry, but I don't know the process from getting code onto the registry. @ingorichter Do you know?

**Comment by ingorichter** [comment]
we need to tar/gzip all the js files in `brackets/src/extensibility/node/` to create the archive for the registry. Then someone with permissions needs to update the registry. I don't have permissions anymore to the server. Before that update, we need to make sure that the changes work locally before updating the live system. I once ran into issues on that system, since the node version might be pretty outdated again and therefore required node_modules might not like it.

**Comment by zaggino** [comment]
@swmitra can someone at @adobe take care of the update for https://github.com/adobe/brackets-registry or can I get access to that machine and work on it? we need to work on getting this merged so we can fix bugs related to brackets not working properly behind a proxy server

**Comment by zaggino** [comment]
updated this PR to be merge-able

**Comment by swmitra** [comment]
@zaggino We are looking into the registry server node upgrade request. Should be able to give you some concrete data by end of this week.

**Comment by saurabh95** [comment]
@zaggino Since the server has upgraded node version, Could you resolve conflicts in this PR?

**Comment by zaggino** [comment]
@saurabh95 Conflicts resolved.

**Comment by swmitra** [comment]
@zaggino Not yet 😄 . Probably becuase I have merged @ficristo PR for write config grunt task. Can you please merge that one more.

**Comment by zaggino** [comment]
@swmitra Done again :-)

**Comment by swmitra** [comment]
Merging this PR. Build failure is because of cla check pull failure.

**Comment by swmitra** [comment]
Thank a ton @zaggino for bringing this change. It makes dependency management a lot more trivial. Great work as always 👍

**Review by swmitra — COMMENTED** [review]
Good to merge as registry server is also upgraded to latest node.

**Pull request merged**
