### PR TITLE
Create index.html

### PR DESCRIPTION
**Pull request by FallingHeart**
zh-cn

### CODE REVIEW

**Comment by FallingHeart** [comment]
zh-cn

**Comment by FallingHeart** [comment]
a Chinese translation

**Comment by FallingHeart** [comment]
@integration

**Comment by ficristo** [comment]
> FallingHeart has NOT submitted the contributor license agreement. See http://dev.brackets.io/brackets-contributor-license-agreement.html.

**Comment by FallingHeart** [comment]
i get a license @ficristo

**Comment by ficristo** [comment]
@FallingHeart do you know someone who could review this ?
I think you are missing an entry in `src/nls/zh-cn/urls.js`: something like: `"GETTING_STARTED"           : "zh-cn/Getting Started"`.
You could also translate the Getting Started words if you want (and the link should be reflected in the GETTING_STARTED above)

**Comment by FallingHeart** [comment]
i am really sorry because i am totally a freshman here
and due to my poor english
i can not really understand what you are talking about
what does it mean by a single PR
what does PR stand for

**Comment by ficristo** [comment]
PR stands for Pull Request, what you have here is a pull request. You can think it as a request to merge your code.
Based on the branch names (patch-1 and patch-2) it seems to me you have used GitHub interface to create these PR. If I remember correctly GitGub interface doesn't allow you to modify more than one file.
Ideally you should have used a local clone of Brackets to change both files and do a single PR with both files modified. But you should also know / learn git commands to do it.

PS: my english is not really good either, I hope to have been clearer.

**Comment by ficristo** [comment]
Superceded by https://github.com/adobe/brackets/pull/13473

**Pull request closed without merging**
