### PR TITLE
Add 'onHighlight' optional event callback mechanism for better extensibility features in hint providers

### PR DESCRIPTION
**Pull request by swmitra**
This PR is targeted to add an optional `onHighlight` hook handling for Code hint providers. This will help extension developers to add interactive workflows when a user crawls over hint items in hint popup. 

@nethip @petetnt All yours now, please have a look at the change set.

### CODE REVIEW

**Review by petetnt — COMMENTED** [review]
Not sure if this should be a Event Emitter instead?

Documentation would be nice to the userguide.

**Comment by swmitra** [comment]
Thanks a lot @petetnt for quick review :+1.

This would be a provider specific implementation. IMHO, scoping the event emitter to a provider will make the listener code ambiguous. Also, keeping this as a hook keeps the reach of the handling very shallow and declaration of the intent is upfront. But that's my thought, want to hear the advantages of event emitter in this case as well.

**Comment by nethip** [comment]
@swmitra LGTM. But +1 on @petetnt comment about documentation.

**Comment by petetnt** [comment]
FWIW I am okay with this _not_ being an event emitter too as code hint list providers provide functions anyway now that I looked at this more 👍

**Comment by swmitra** [comment]
@nethip @petetnt Added this to our wiki for code hint API's. 
https://github.com/adobe/brackets/wiki/New-Code-Hinting-API-Proposal

**Comment by nethip** [comment]
Thanks @swmitra

**Comment by swmitra** [comment]
Thanks @nethip 😃

**Pull request merged**
