### PR TITLE
Use opn instead of open.

### PR DESCRIPTION
**Pull request by ficristo**
Installed with node@3 and npm install --production

### CODE REVIEW

**Comment by petetnt** [comment]
This line: https://github.com/adobe/brackets/blob/656a0ee1d9889e853a77a4d9b12b9a82e6f86c55/src/LiveDevelopment/MultiBrowserImpl/launchers/node/LauncherDomain.js#L29 needs to be changed to `var open = require("opn");` too right?

**Comment by ficristo** [comment]
@petetnt of course... fixed.

**Comment by MarcelGerber** [comment]
I _think_ we need some sort of https://github.com/adobe/brackets-shell/pull/505/files for this one, too, so it works when installed with the .deb file.
LGTM otherwise.

**Comment by ficristo** [comment]
> we need some sort of
I guess I learn something every day

I've opened two PR one for maste and one for linux-1547 branch on brackets-shell

**Comment by MarcelGerber** [comment]
LGTM. Also tested this with an installer build on Linux to make sure it works.
Merging.

**Pull request merged**
