### PR TITLE
v1.0 czech language

### PR DESCRIPTION
**Pull request by ghost**
updated

### CODE REVIEW

**Comment by ingorichter** [comment]
@kvarel Thanks for the translations updates. It seems there is only one little thing missing before we can merge this. Are you able to get back to it and make the changes? It would be great to have this updated translation available for our users. Thanks a lot.

**Comment by dvorapa** [comment]
Could you merge the translation into v1.2 and put that line on hold? Or write it on your own?

**Comment by busykai** [comment]
@dvorapa, it seems like @kvarel is unresponsive. could you take care of completing this PR? you'll need to branch off `kvarel:patch-14`, make the changes (sha and url) and create another PR off that new branch.

**Comment by dvorapa** [comment]
Should be resolved by #10503

**Comment by ingorichter** [comment]
Should we close this PR in favor of #10503?

**Comment by busykai** [comment]
Yes, I'm closing this in favor of #10503. Kudos to @kvarel for the initial translation! The original commit is properly included into the other PR.

**Pull request closed without merging**
