### PR TITLE
Azerbaijani language

### PR DESCRIPTION
**Pull request by ziyaddin**

### CODE REVIEW

**Comment by abose** [comment]
Thanks @ziyaddin for submitting the new language.
I could not find the option for Azerbaijani in the language select menu at `debug>switch language`. Could you check that out.

**Comment by ziyaddin** [comment]
Thank you @abose for support.
Sorry, I couldn't understand you. What is the issue?

**Comment by sprintr** [comment]
You need to add `"LOCALE_AZ" : "Azerbaijani"` to `src/nls/root/strings-app.js`, so `Azerbaijani` can appear in `Debug > Switch Language`. Right now it is only showing `az`.

**Comment by abose** [comment]
@ziyaddin also could you add any other contributor who can review the translations?

**Comment by abose** [comment]
@ziyaddin Thanks for the pr, we would need alease the top level menus and all its contents to be traslated into az befoe we can add this to the list of supported languages. Could you contribute the remaining translations for the top level menus and its contents?

**Comment by abose** [comment]
Closing pr as not answered.
@ziyaddin Please reopen this after the updates.

**Comment by ziyaddin** [comment]
Sorry @abose for no answer. Once I translate the remaining strings, I will reopen it.

Cheers,

**Pull request closed without merging**
