### PR TITLE
Update Finnish strings

### PR DESCRIPTION
**Pull request by valtlai**

### CODE REVIEW

**Comment by narayani28** [comment]
I plan to merge this PR to master and hence please address the pending issue on the PR for the error message "All checks have failed".

**Comment by valtlai** [comment]
@narayani28 I have no idea why the tests failed. Someone with the privileges should rerun Travis CI.

**Comment by valtlai** [comment]
Closing and reopening to restart Travis CI.

**Comment by valtlai** [comment]
I don’t want to sign the new CLA, so closing.

**Pull request closed without merging**
