### PR TITLE
Upgraded CodeMirror version to 5.28.0

### PR DESCRIPTION
**Pull request by saurabh95**

### CODE REVIEW

**Comment by ficristo** [comment]
You should also change `npm-shrinkwrap.json` in the src folder.
Have you run the test suite with this PR?

**Comment by saurabh95** [comment]
Yeah, I have run the test suite on the upgrade.

**Review by ficristo — APPROVED** [review]
If it doesn't introduce any failure, merge it! 😄

**Review by petetnt — APPROVED** [review]

**Comment by petetnt** [comment]
Fixes #13590

**Pull request merged**
