### PR TITLE
Move PathUtils to Brackets core code

### PR DESCRIPTION
**Pull request by ficristo**
Fix for #11726.

### CODE REVIEW

**Comment by zaggino** [comment]
Reviewed, looks good to me.

**Comment by ficristo** [comment]
I think, based on the discussion on #11726, this needs to be reverted.
It can always be relanded, and we can even add better comments.

**Comment by peterflynn** [comment]
@zaggino Just catching up on 1.5 PRs... is this a breaking change for any extensions that were using PathUtils?  (The path has changed).  Did you check the ExtensionGrabber tree to see if any / how many extensions wold be broken by this?

**Comment by peterflynn** [comment]
Ah nm, I see that this was reverted a day later.

**Pull request merged**
