### PR TITLE
Fix #13274 - make Brackets margin/padding remoteHighlight work like Chrome one

### LINKED ISSUE #13274: [Live preview] Improve the appearance of transformed elements when showing margins/paddings
### Steps to Reproduce

1. Enable highlighting elements in Live Preview
2. Reenable transform to custom-highlightning divs in `RemoteFunctions.js` (it is not applied atm)
2. Transform it via CSS, ex. `rotate:90deg`.
3. As you can see, the margin/paddings showed differ from those in Chrome DevTools

**Expected behavior:** Elements are highlighted the same way as DevTools does

**Actual behavior:** Their size differs due to `window.getClientBoundingRect` (it includes transform and causes the bugs in calculations) 

See https://github.com/adobe/brackets/pull/12949#issuecomment-268806531 for more details.

### PR DESCRIPTION
**Pull request by Worie**
Added support for `transform-origin` and fixed the way of showing `border` in highlight div.

This contains a little bit more of changes than the previous one and probably will need a bit of refactor, but it should work. Please mention me if it isn't working for some sets of properties and provide the piece of code that does not look correct.

I've tested/developed it on OSX Sierra 10.12.4, Chrome 57.0.2987.133 (64-bit)

### CODE REVIEW

**Comment by saurabh95** [comment]
The issue which I mentioned in the last PR is resolved now.

**Comment by Worie** [comment]
@swmitra what do you think?

**Comment by swmitra** [comment]
It seems to be working fine 👍 
Let me have a look at the change set ...

**Review by swmitra — APPROVED** [review]
Tested the feature manually. Working fine for different scenarios I have tested. Changeset seems good to me.

**Comment by swmitra** [comment]
Good work worie 👍 
Merging the PR, this will give us more time to identify issues (if any) well before 1.10 release.

**Comment by swmitra** [comment]
@worie I am working on the same set of files for some other feature. I will refactor it in my PR 😄

**Comment by Worie** [comment]
Awesome! I'm glad it turned out ok, feel free to ping me if necessary :)

**Pull request merged**
