### PR TITLE
Update CodeMirror

### PR DESCRIPTION
**Pull request by marcelgerber**
See #12609.
cc @ficristo 
I ran Unit, Integration and Extension tests without new failures.

### CODE REVIEW

**Comment by ficristo** [comment]
It seems to me you have used the commit of the CodeMirror repository instead of using the adobe/CodeMirro2: I am unable to update the submodule.
In future can you write in the commit message the version we are going to update? Thank you.

**Comment by MarcelGerber** [comment]
Ah, sorry, I forgot to push the updated version to our CodeMirror2 fork. I've done so now so you can try again.

**Comment by MarcelGerber** [comment]
I have pulled the test fixes in, so you can have another look.

**Comment by ficristo** [comment]
Sorry but I don't think I'll have much time this or the next week to review this PR.
I saw a couple of fixes about backtips on JS scripts on latest master of CodeMirror: I would really like to take them. People is doing more and more ES6 stuff.

So I see at least two options:
- land this as is. I think CodeMirror is stable enough that if doesn't introduce new errors in the Brackets test suite should good to go. The 1.7 release was released recentish enough that I _think_ we have enough time to verify eventual regressions. (And take another upgrade next months)
- wait the next release and meanwhile continue to test this PR and fixing the current tests failures

/cc @petetnt @MiguelCastillo @zaggino if they have more thoughts.
(I don't know how were tested the previous versions so having other opinions is good regardless)

**Comment by MarcelGerber** [comment]
Just so you know, we usually update to some commit of CodeMirror, not necessarily to a release version (in-between versions of CodeMirror are usually stable as well), so we can take in these recent fixes without problems.
Our testing process is mostly just running all the unit tests, merging, and then looking out for regressions in the issue tracker.

**Comment by zaggino** [comment]
:+1: for merge

**Comment by ficristo** [comment]
Ok, if you update against latest CodeMirror master and tests pass (or at least doesn't introduce new failures) is fine by me.

**Pull request merged**
