### PR TITLE
Translate in Italian language for Brackets 1.3

### PR DESCRIPTION
**Pull request by Denisov21**

### CODE REVIEW

**Comment by rroshan1** [comment]
@Denisov21 Can you please pull from the release branch and make these changes there (except the release version changes) and then create a PR.
It would be great if you could also add someone for linguistic review.

**Comment by Denisov21** [comment]
I had some difficulty in changing branch as you can see @rroshan1. Prefer close this PR, and later I'll make another.

**Comment by rroshan1** [comment]
Ok @Denisov21. 
Bdw, we can request @Fredev from #10993 for Italian linguistic reviews.

**Comment by Fredev** [comment]
Hello, after #10993 I had the time to take a better look at the Italian strings file, I found more errors among which: a lot of Italian semantic mess, miss of consistency with the root strings file, some 'Brackets' instead of {APP_NAME} and much more, soooo, I would be very very happy to contribute for a complete review of the Italian translation of brackets!

**Comment by Denisov21** [comment]
Hello @Fredev, the project is open source. Of course if you find errors feel free to create a new Pull Request for Italian Language!

**Pull request closed without merging**
