### PR TITLE
Drastically improve QuickView performance for long lines

### PR DESCRIPTION
**Pull request by marcelgerber**
For #10879.

Enables TokenUtils caching (for both `getTokenAt` and `getModeAt`) and moves the `areParensBalanced` call out of the loop.

Also, in `getModeAt` it first checks whether the mode actually has inner mode support ([that's what CodeMirror does, too](https://github.com/codemirror/CodeMirror/blob/f7a00e0b0c138186232786f547b38e3e2f9cba5d/lib/codemirror.js#L4896-L4900)).

### CODE REVIEW

**Comment by MarcelGerber** [comment]
Could we maybe merge this now that Release 1.4 has just begun so this has a long testing phase?
It improves performance when looking at minified files...

**Comment by prafulVaishnav** [comment]
@MarcelGerber Sure. Picking it for review..

**Comment by nethip** [comment]
@MarcelGerber Thanks for this! Did you run unit tests especially the ones relating to the Editor?

**Comment by MarcelGerber** [comment]
I've ran all unit, integration & QuickView extension tests. All tests passed.

**Comment by nethip** [comment]
@prafulVaishnav Did you get a chance to review this?

**Comment by prafulVaishnav** [comment]
LGTM merging.. Thanks @MarcelGerber

**Pull request merged**
