### PR TITLE
fix InlineImageViewer example extension

### PR DESCRIPTION
**Pull request by kidwm**
and separate the filename and close button.

### CODE REVIEW

**Comment by nethip** [comment]
@kidwm Could you move the in line styles to a style sheet? We could then go ahead and merge this change.

**Comment by kidwm** [comment]
@nethip I've done it.

**Comment by nethip** [comment]
@kidwm Thanks! I would do a quick round of testing and merge this.

**Comment by ficristo** [comment]
@nethip @kidwm What is the status of this?

**Comment by ficristo** [comment]
LGTM, ideally the filename could be near the X to match other QuickEdit.
But at least now it works again.

@kidwm thank you.

**Pull request merged**
