### PR TITLE
Add Korean Getting Started Page in samples. 

### PR DESCRIPTION
**Pull request by JungGaBin**
*Add Korean index.html.

*Add Korean main.css.

*Add Korean screenshots.

*Add Korean Getting Started Page URL.

*Correct typo.

### CODE REVIEW

**Comment by ficristo** [comment]
In src/nls/ko/urls.js you should add an entry like: "GETTING_STARTED" : "ko/Getting Started",
I'll try to find more time this weekend to check this PR.
In the meantime if you know some korean people who can help to help to check the translations, it would be nice.

**Comment by JungGaBin** [comment]
@ficristo 
Okay,
I will fix it as soon as possible.

**Comment by JungGaBin** [comment]
@ficristo 
Please note the PR that created the Korean Getting Started Page is in #13846  .
"Correct typo" is missing from this #13846 .

**Comment by ficristo** [comment]
Duplicate of #13846
The translations can be updated in their own PR.

**Comment by JungGaBin** [comment]
@ficristo 
Okay, i got it.

**Pull request closed without merging**
