### PR TITLE
Update strings.js

### PR DESCRIPTION
**Pull request by tonivj5**
fix small error

### CODE REVIEW

**Comment by abose** [comment]
@xxxtonixxx We need you to sign the Brackets contributor agreement (CLA) before we can merge this. http://dev.brackets.io/brackets-contributor-license-agreement.html

**Comment by xxxtonixxx** [comment]
Ok! I have already accepted it :thumbsup:

**Comment by rroshan1** [comment]
Changes look good. Merging.

**Comment by TomMalbran** [comment]
Woops. Thanks for the fix.

**Pull request merged**
