### PR TITLE
Hint color names in CSS Code Hints

### PR DESCRIPTION
**Pull request by marcelgerber**
Shows color names in Code Hints for CSS properties like `color`, `background-color`, `border-left-color`, ...

image

### CODE REVIEW

**Comment by le717** [comment]
Unless I'm missing something, you've completely removed `currentColor`. `currentColor` is a valid "color" with special meaning, and a [standardized CSS3 spec](http://www.w3.org/TR/css3-color/#currentcolor).

**Comment by MarcelGerber** [comment]
Oh, I didn't know this was a valid value.
Will add it back tomorrow.

**Comment by MarcelGerber** [comment]
@le717 Done.

**Comment by redmunds** [comment]
@MarcelGerber Very cool! Merging.

@sprintr This same technique can be used to add named colors back into SVG code hints.

**Comment by le717** [comment]
@MarcelGerber  @redmunds Thanks for merging this! :D This has always been a curious missing feature for me, considering the built-in color editor

**Comment by MarcelGerber** [comment]
Thanks for merging :)
We can possibly add a "color preview bagde" later on (a badge on the right of the hints popup), but I need to have a look at the code before.
Can a hint provider combine jQuery & rawtext hints?

**Comment by RaymondLim** [comment]
@MarcelGerber Yes, you can combine raw text hints with jQuery as in the following example I used in my "user key map hints" (not in the repo yet).

code snippet in `getHints` that appends the assigned key to raw text command id.
```
            result = $.map(this._allCommands, function (value, key) {
                if (value.toLowerCase().indexOf(query.toLowerCase()) === 0) {
                    if (self.keyMap[value]) {
                        return value + "&nbsp;<span class='display-key'>" + self.keyMap[value] + "</span>";
                    } else {
                        return value;
                    }
                }
            }).sort();
```

code snippet in `insertHint` that extracts command id by excluding the appended key.
```
        if (hint.indexOf("&nbsp;") !== -1) {
            hint = hint.slice(0, hint.indexOf("&nbsp;"));
        }
```

**Pull request merged**
