### PR TITLE
Replace 'smart autocomplete' with a purpose-built QuickSearchField module

### PR DESCRIPTION
**Pull request by peterflynn**
Simplifies QuickOpen code -- trimming out about 200 lines -- removing workarounds and allowing it to use the ModalBar autoClose option. Fixes bugs with arrow key handling, cleans up APIs, and more consistently highlights the item that pressing enter will select.

Fixed issues include: #5871, #3405, #5360, #2757, #5029, #6646, #3444, #1550, #333, #7367, #8063, #9283, an unfiled bug where pressing the right arrow key closes Quick Open instead of moving the cursor, and #652 (which may reduce the priority of #6203 since it's the only user-visible part of that issue).  I'm _guessing_ this also fixes #5344.

~~There are still some loose ends to polish up here (unit tests & removing logging code) -- so it's definitely not ready to merge yet.~~
Unit tests added, code is ready for review now!

### CODE REVIEW

**Comment by le717** [comment]
@peterflynn Is this planned to be land in 1.3? I can't seem to find a list of major changes/improvements that's planned for 1.3, and I would think this would be a good PR to land.

**Comment by peterflynn** [comment]
Whew, well... only about a year late, I finally have this caught up with master and in good shape to merge :-)  I've addressed all of @ingorichter's code review comments and fixed one lingering problem with up/down arrow keys.  I ran off this branch all day with no problems, so it seems solid.

Until recently, the user-facing benefits of this PR were pretty subtle (it was mostly about maintainability).  But it appears to fix #9283, which is a pretty high-visibility CEF 2171 regression, so that makes it more valuable to get into 1.3.  @nethip do you have time to review in the next week or so any any chance? (I'm assuming Ingo doesn't have the cycles)

**Comment by nethip** [comment]
Hey @peterflynn Sorry I somehow missed this. I am already going through the long list of files in this PR? The changes seem to be fine. I will do a quick round of unit testing and merge this. Thanks!

**Comment by peterflynn** [comment]
Thanks @nethip!

**Comment by nethip** [comment]
Thanks @peterflynn!

**Comment by rroshan1** [comment]
@peterflynn The QuickOpen Integration Tests are failing on this merge (used git bisect). 
The 3 Tests fail with the message "timeout: timed out after 3000 msec waiting for file opening timeout" due to 'editor = EditorManager.getCurrentFullEditor();' never being assigned a non-null value.

Could you please give me some pointers so that I could fix this Test failure.

**Comment by nethip** [comment]
@rroshan1 This looks like a time out issue. Have you tried increasing the time limit to say 10 secs and try running the tests?

**Comment by rroshan1** [comment]
@nethip Yes, I have tried increasing the time limit but that does not seem to fix it.

**Comment by rroshan1** [comment]
QuickOpen Test failures resolved with PR #10922.

**Pull request merged**
