### PR TITLE
Fix for #3296: add deprecation warning for global Mustache

### PR DESCRIPTION
**Pull request by ficristo**
There are still some references in test/perf/OpenFile-perf-files/brackets-concat.js, but the file seemed autogenerated so I didn't changed it.
#3296

### CODE REVIEW

**Comment by ingorichter** [comment]
@ficristo Would you mind resolving the conflicts? Thanks.

**Comment by ficristo** [comment]
@ingorichter I have updated the patch.

**Comment by ficristo** [comment]
@ingorichter I've rebased the patch.

**Comment by ficristo** [comment]
@MarcelGerber could you review this?

**Comment by MarcelGerber** [comment]
LGTM. Only minor thing is that you should be able to remove https://github.com/adobe/brackets/blob/656a0ee1d9889e853a77a4d9b12b9a82e6f86c55/Gruntfile.js#L277 as well.

**Comment by ficristo** [comment]
@MarcelGerber done.

**Comment by MarcelGerber** [comment]
Thank you!
Merging.

**Pull request merged**
