### PR TITLE
Allow CSS Code Hints in PHP files

### LINKED ISSUE #11629: Code hint/completion regardless of extension
I don't know if this is an error or as intended but I can not under any circumstances get code completion for my css to appear if the file extension is .php.

It will complete the tag... "&lt;style&gt;" "&lt;/style&gt;" but if I add a class and begin entering style definitions, the popup window with suggestions never appears... however If I simply change the file extension to "html" and start typing the same style under my class it works as expected.

I believe this may be an error as it works correctly inside javascript tags regardless if the extension is PHP. Whether or not this is an error it would be nice to see it resolved so CSS would auto-complete regardless of file extension, Furthermore I have tried many different preference changes to no avail but if there is some workaround now that would be great.

### PR DESCRIPTION
**Pull request by sprintr**
Allow CSS Code Hints in style tags for PHP files. Fixes #11629

### CODE REVIEW

**Comment by MarcelGerber** [comment]
There are 3 more occurences of `ctx.token.state` in https://github.com/sprintr/brackets/blob/2e64c0dfd7ec8b15365438068720ce1fa59df480/src/language/CSSUtils.js#L1583-L1592

Please try to fix those as well. In my opinion, a helper function `_getState` would fit all cases the best.

**Comment by abose** [comment]
Tagging @MarcelGerber for review.

**Comment by MarcelGerber** [comment]
@sprintr There are _still_ 3 occurences of `ctx.token.state`. You should switch them over to `_getState()`, or state that they should not be changed for some reason.

**Comment by sprintr** [comment]
Closing in favor of #11751

**Pull request closed without merging**
