### PR TITLE
Implemented whole word search

### LINKED ISSUE #11621: Wish: "whole words only"
Adding the command search for "whole words only" in the commands "Find"

### PR DESCRIPTION
**Pull request by ficristo**
Written on top of https://github.com/adobe/brackets/pull/11614
Should fix https://github.com/adobe/brackets/issues/11621
If someone could provide me the icons (or create them post merge) I think this patch is ready.

### CODE REVIEW

**Comment by ficristo** [comment]
See https://github.com/adobe/brackets/pull/9526 too.

**Comment by ficristo** [comment]
Closing as duplicate.

**Comment by abose** [comment]
@ficristo I prefer this to #9526

**Comment by ficristo** [comment]
@abose This PR still miss the icon and probably some tests.
Plus after all the effort that @MarcelGerber has put in it I'm not really keen to revive this PR.

**Pull request closed without merging**
