### PR TITLE
Addresses #13264 where setting `saveFoldStates` preference to false caused folding problems

### PR DESCRIPTION
**Pull request by thehogfather**
This PR properly initialises the `_lineFolds` cache to the empty object when the saveFoldStates preferences is set to false. Previously, this was not being done and it caused issues down stream, i.e., when rendering gutters as the active editor changed.

Also updated the test cases to accommodate the requirement.

cc @lkcampbell @ficristo

### CODE REVIEW

**Comment by lkcampbell** [comment]
@thehogfather, the changes look good to me. Initialize the uninitialized property with an empty object and get rid of the undefined/null error message down the road. 

Is `_codeMirror._lineFolds` where you are storing all of the fold state information for each instance of CodeMirror opened in brackets?

The only problem I see is the Travis build is failing. @ficristo or @petetnt any ideas what might be causing the build fail?

**Comment by thehogfather** [comment]
@lkcampbell 
>Is _codeMirror._lineFolds where you are storing all of the fold state information for each instance of CodeMirror opened in brackets?

Yes that is correct.

With respect to Travis failing, I'll pull upstream and push to trigger the build again. The error messages show it did not get very far into the build process.

**Comment by thehogfather** [comment]
That did no seem to help. Let me know if there is anything I can do.

**Comment by petetnt** [comment]
Restarted the CI by hand, I'll look into it if it still fails

**Comment by swmitra** [comment]
I was just trying out with the OAuth token and couldn't exceed the limit in 60 attempts. Not sure why this one failed!

**Comment by ficristo** [comment]
Fixes #13264 (adding this comment so GitHub creates a link to the issue)

**Review by ficristo — APPROVED** [review]

**Comment by lkcampbell** [comment]
Okay, I check that the fix works and ran the unit tests: no errors.

Merging.

**Pull request merged**
