### PR TITLE
Updated copyright to 2016

### PR DESCRIPTION
**Pull request by maqnouch**

### CODE REVIEW

**Comment by Denisov21** [comment]
Hi,
@aqnouch must submitted the contributor license agreement. See http://dev.brackets.io/brackets-contributor-license-agreement.html

Thank @aqnouch for this PR!

**Comment by sprintr** [comment]
Make sure to update it in the [about dialog](https://github.com/adobe/brackets/blob/master/src/htmlContent/about-dialog.html#L16) as well.

**Comment by ficristo** [comment]
Superseeded by #12092.

**Comment by MarcelGerber** [comment]
Closing in favor of #12092 (already merged).
Thanks anyway!

**Pull request closed without merging**
