### PR TITLE
[CEF 2623] Upgrade to latest CEF

### PR DESCRIPTION
**Pull request by nethip**
With latest CEF, quick open is not showing the results as opacity was set to 0. So removed opacity for .quick-search-container

This is required for updating shell APIt
Related PR :https://github.com/adobe/brackets-shell/pull/544

### CODE REVIEW

**Comment by nethip** [comment]
@swmitra Could you have a look at this PR?

**Comment by nethip** [comment]
@MarcelGerber @ingorichter @peterflynn  Would you guys be able to review this PR?

**Comment by Denisov21** [comment]
:+1: Good for me!

**Comment by MarcelGerber** [comment]
@nethip I have altered this PR by actually fixing the `.animation` LESS mixin (which was the reason why Quick Open failed), fixing it in other locations, too, and adding `opacity: 0` back.

**Comment by nethip** [comment]
@MarcelGerber thanks for fixing the actual problem.

**Comment by swmitra** [comment]
LGTM.
Kudos to @nethip :+1: for this PR and the related PR in brackets-shell. 
Great job by @MarcelGerber by providing quick fix for the quick open issue :+1: 
Merging...

**Pull request merged**
