### PR TITLE
Revert "Move PathUtils to Brackets core code"

### PR DESCRIPTION
**Pull request by zaggino**
Reverts adobe/brackets#11734 as requested in comment and discussion in #11726

### CODE REVIEW

**Comment by zaggino** [comment]
@busykai feel free to hit the merge button

**Comment by abose** [comment]
Reverted as per discussions in #11726

**Comment by busykai** [comment]
Thanks @zaggino and sorry we had to do it.

**Comment by petetnt** [comment]
The latest master is broken and `git bisect` points to this commit. Hmm?

**Pull request merged**
