### PR TITLE
Bumping version Number to 1.9

### PR DESCRIPTION
**Pull request by shubhsnov**
@swmitra Please review.

### CODE REVIEW

**Comment by swmitra** [comment]
LGTM 👍

**Review by swmitra — APPROVED** [review]

**Comment by swmitra** [comment]
Merging now.

**Comment by aniddan** [comment]
Why can't I download it?

**Comment by swmitra** [comment]
@aniddan 1.9 is the development version.  Once it's released ( Mar 3 tentatively) , you should be able to download. Meanwhile if you want to use tip of the Brackets repo , then clone and hack your install version.

**Comment by aniddan** [comment]
Generally it's better that the version will reflect the last stable version

**Pull request merged**
