### PR TITLE
Czech translation for v1.1

### PR DESCRIPTION
**Pull request by dvorapa**
- Translated two strings
- Translated several comments
- Synced with root/strings.js (for easier comparison in future translations)
  - Fixed some extra/missing space
  - Switched several lines
- Fixed grammatical mistakes

### CODE REVIEW

**Comment by peterflynn** [comment]
@dvorapa Can you close this and submit a new pull request targeted at the `release` branch?

**Comment by dvorapa** [comment]
Sure, see #10576

**Comment by dvorapa** [comment]
Sure, see #10576

**Comment by peterflynn** [comment]
Thanks!

**Pull request closed without merging**
