### PR TITLE
Czech translation for v1.6

### PR DESCRIPTION
**Pull request by dvorapa**
PR to `adobe:release` branch

### CODE REVIEW

**Comment by ficristo** [comment]
Now that 1.6 is out I think this is not needed anymore.

**Comment by dvorapa** [comment]
@ficristo It is needed for v1.7 (see https://github.com/adobe/brackets/pull/11834#issuecomment-149140183). But I don't understand, why there is a call for translation PRs on Google Groups, if devs finally don't merge some of them.

**Comment by ficristo** [comment]
I think is not needed because you have already #12046 for 1.7.
Am I wrong?

**Comment by dvorapa** [comment]
@ficristo yes, you are wrong, #12046 is the same as this, just into master branch (this is into release branch).

**Comment by abose** [comment]
@dvorapa Thanks for the change. Apologies for not merging this for 1.6.
Closing in favor of https://github.com/adobe/brackets/pull/12046 .

**Pull request closed without merging**
