### PR TITLE
Update CSS Code Hints properties

### PR DESCRIPTION
**Pull request by valtlai**
Add properties
– `all`
– `caret-color`
– `grid-template`
– `hanging-punctuation`
– `isolation`
– `mix-blend-mode`
– `scroll-behavior`
– `tab-size`
– `user-select`.

Add values:
– `clone` and `slice` for `box-decoration-break`
– `contents` and `subgrid` for `display`.

Remove deprecated `padding-box` from `box-sizing`.

Fix the order of `background-blend-mode`.

### CODE REVIEW

**Comment by ficristo** [comment]
Overall it seems good to me, I'm still not sure if the values `inherit`, `initial`, `unset` should be added or not.
It seems that sometime they were and sometime not.
@swmitra ?

**Comment by valtlai** [comment]
@fristo Every CSS property has values `inherit`, `initial`, `unset` and `revert`. I think they should be added automatically and removed from `value` fields.

**Comment by swmitra** [comment]
@valtlai Agreed. These 4 values are CSS wide property values and applicable to all properties. 
'padding-box' can be removed as most of the modern browsers are skipping this at the moment.  
Other changes looks good to me as well. 

Good work 👍

**Review by swmitra — APPROVED** [review]

**Comment by swmitra** [comment]
Merging now.

**Pull request merged**
