### PR TITLE
Changed Global.js to enable Native Menus for Linux

### PR DESCRIPTION
**Pull request by saurabh95**
We can merge this only after this https://github.com/adobe/brackets-shell/pull/602 is merged.

### CODE REVIEW

**Review by swmitra — APPROVED** [review]
LGTM. Lets wait for the shell PR to be merged.

**Comment by ficristo** [comment]
I think you can also remove this check: https://github.com/adobe/brackets/blob/6da0c76f2c41092aff26792c8b6dfccebe457524/test/spec/NativeMenu-test.js#L32
(and verify tests pass on Linux)

**Comment by saurabh95** [comment]
@ficristo I have enabled Native Menu tests for Linux, they are passing :smile:

**Review by ficristo — APPROVED** [review]

**Review by petetnt — APPROVED** [review]

**Comment by swmitra** [comment]
Merging now.. 
The dependency on Brackets shell is already resolved by merging https://github.com/adobe/brackets-shell/pull/602.

**Pull request merged**
