### PR TITLE
Project Preferences File Corruption Issue

### PR DESCRIPTION
**Pull request by rroshan1**
Fix for #10757 .
Error message appears if the Global Preferences file (brackets.json) is corrupted and the file is opened in editor for editing. Added similar functionality for project level Preferences File (.brackets.json).

### CODE REVIEW

**Comment by rroshan1** [comment]
@peterflynn Can you please review this?

**Comment by prksingh** [comment]
@rroshan1 I have some time to review it. Assigning to myself

**Comment by prafulVaishnav** [comment]
@rroshan1 I think we should make the change in the Preference files where all the stuff related to preferences are handled.

**Comment by prksingh** [comment]
@prafulVaishnav I see that we have similar check for the global preference file in brackets.js, so a similar check in projectManager for checking project specific preference appears fine to me.

**Comment by prksingh** [comment]
Merging.

**Pull request merged**
