### PR TITLE
Fix #11900

### LINKED ISSUE #11900: Translations: DEFAULT_PREFERENCES_JSON_HEADER_COMMENT in Japanese
The current translation of DEFAULT_PREFERENCES_JSON_HEADER_COMMENT in Japanese is:
```
/*
 * これは、{APP_NAME} で環境設定がサポートされた
読み取り専用ファイルです。
 * このファイルは、他のペインで開かれた環境設定ファイル brackets.json を
 * 変更する際の参照資料として使用します。
 * {APP_NAME} 内で環境設定を使用する方法については、Web ページ
 *  (https://github.com/adobe/brackets/wiki/How-to-Use-Brackets#preferences) を参照してください。
 */
```

This translation has some issues:
- Its word wrapping is random.
- The first sentence 「これは、Brackets で環境設定がサポートされた読み取り専用ファイルです。」 is broken and impossible to understand.
- The subject of the second sentence 「このファイルは、他のペインで開かれた環境設定ファイル brackets.json を変更する際の参照資料として使用します。」 is ambiguous. The original sentence is an imperative form, so the translation should be modified to preserve the meaning.

The following is my trial translation:
```
/*
 * これは、{APP_NAME} がサポートしている環境設定が記録された読み取り
 * 専用ファイルです。
 * もう片方のペインで開かれた環境設定ファイル brackets.json を変更
 * する際の参考としてお使いください。
 * {APP_NAME} 内で環境設定を使用する方法については、Web ページ
 * https://github.com/adobe/brackets/wiki/How-to-Use-Brackets#preferences
 * を参照してください。
 */
```

### PR DESCRIPTION
**Pull request by mandel59**

### CODE REVIEW

**Comment by ficristo** [comment]
@mandel59 If you haven't seen, you should sign the CLA:
`mandel59 has NOT submitted the contributor license agreement. See` http://dev.brackets.io/brackets-contributor-license-agreement.html.

@abose Is the japanese translation handled differently from the others? I see only `walf` to have committed to it.

**Comment by mandel59** [comment]
I agreed to the CLA.

**Comment by petetnt** [comment]
@ficristo the japanese translation is from ALF automation system, which I think is Adobe's automated string translation system.

**Comment by abose** [comment]
@petetnt That's right. Adobe maintains Japanese translations. 
Closing.
@mandel59 Could you provide some information regarding why this change was done so that we could transfer the case to our translation vendors?

**Comment by petetnt** [comment]
@abose the details are in https://github.com/adobe/brackets/issues/11900

**Comment by abose** [comment]
Have forwarded this issue to the internal translations team. Will be mostly considered in the next round of translations.

**Comment by KatarzynaWodzinska** [comment]
Hi All! Our linguist agreed with the proposed correction.The JP string has now been fixed.

**Pull request closed without merging**
