### PR TITLE
Move CodeMirror on node_modules

### PR DESCRIPTION
**Pull request by ficristo**
What I had in mind was something like this.
I think this will NOT work on distribution since the node_modules would be in a different location.
Also I find worrisome I had to change the css link.

Ref #12940

### CODE REVIEW

**Comment by zaggino** [comment]
Looks good to me, let's test how the distribution mode works.

**Comment by ficristo** [comment]
Otherwise we could put another `package.json` in the `src` folder.
But the two `package.json` doesn't seem necessary anymore with the newer versions of electron-builder and I think this is a bit of a contributor barrier.
I still don't have any idea how to change the path for distribution in case of single `package.json`.
At this point I don't have strong opinions: thoughts?

**Comment by swmitra** [comment]
@ficristo The changes looks good to me. But I have a different question. When I tried to check the changes on my local machine, I had to do a npm install. Is that expected when someone clones the repo for dev setup?

**Comment by zaggino** [comment]
@swmitra yes, `npm install` is expected, it has also been added here: https://github.com/adobe/brackets/wiki/How-to-Hack-on-Brackets#setting-up-your-dev-environment

**Comment by ficristo** [comment]
I tryed to hack something but I wasn't able to make `grunt build` to pass. (In the specific `grunt requirejs`)
If nobody has some bright idea I don't think this will work, as is, on distribution.
I'll create a new `package.json` inside `src` and see how this will work.
Of course #12940 is still a choice.

**Comment by ficristo** [comment]
Closing in favor of #12972.

**Pull request closed without merging**
