### PR TITLE
Don't show hints inside a regexp.

### LINKED ISSUE #10160: [Code Hints] Code hinting should be disabled in regexps
While I write regular expressions, Brackets shows js variables:

regex-code-hints

### PR DESCRIPTION
**Pull request by RaymondLim**
This fixes #10160.

### CODE REVIEW

**Comment by peterflynn** [comment]
@RaymondLim Can we add unit tests too?

**Comment by RaymondLim** [comment]
@redmunds Thanks for testing in html files. I fixed that issue and will add unit tests later.

**Comment by nethip** [comment]
@RaymondLim Do you have some bandwidth to add unit tests. or should we go ahead with the commit and add test cases later?

**Comment by RaymondLim** [comment]
@nethip Sorry, I don't have bandwidth to add unit tests. Can one of you add them later? Thanks.

**Comment by prksingh** [comment]
Merged PR. Starting a new request for the unit tests

**Pull request merged**
