### PR TITLE
 Caching $(".modal-body", $dlg) in to its own variable

### LINKED ISSUE #10611: Reset extension manager's scroll position to top on filtering
When you search/filter extension manager's results after you have already scrolled down, the scroll position will be incorrectly remembered (if applicable), or it will scroll down to the last item if there are less results than your current scroll position.

When a new search is performed, scrolling should be reset to the top.

### Steps to reproduce
1. Open extension manager
2. Scroll all the way to the bottom on available extensions
3. Search for "doc"

### Actual result
You're viewing the least relevant(?) results at the end of the list.

### Expected result
To be scrolled to the top of panel for the most relevant matches.

### PR DESCRIPTION
**Pull request by mansimarkaur**
Fixes #10611

### CODE REVIEW

**Review by zaggino — CHANGES_REQUESTED** [review]
@mansimarkaur this is good, but I think it misses two lines @darkcoderrises added in https://github.com/adobe/brackets/pull/11378 which @ficristo reviewed ... the PR as it is, won't fix #10611 by itself, will it?

**Comment by mansimarkaur** [comment]
@zaggino I'm sorry. I assumed his PR was merged. I should've checked. I've added the required changes in the above commit.

**Review by zaggino — APPROVED** [review]

**Comment by zaggino** [comment]
@ficristo can you review this since you've looked at this before?

**Comment by ficristo** [comment]
I never looked closely at it. I'll see if I can take a look at the weekend.
@zaggino but if you have already reviewed the PR, and is fine for you, you can merge.

**Comment by zaggino** [comment]
Merged, thanks for the PR @mansimarkaur

**Pull request merged**
