### PR TITLE
String tweaks for Mac 'command line shortcut'

### PR DESCRIPTION
**Pull request by peterflynn**
String tweaks, and ensure URLs shown in dialogs for this feature include a tooltip of the URL.

Examples of the new strings in use:

screen shot 2015-04-13 at 1 35 18 pm

screen shot 2015-04-13 at 4 31 57 pm

### CODE REVIEW

**Comment by peterflynn** [comment]
One of Mac's many little mysteries: why two screenshots I took on the same computer on the same day seem to have different color profiles (e.g. notice the "OK" button color).  Go figure... :-P

**Comment by nethip** [comment]
Thanks for these string changes! @ryanstewart Could you please review these strings if they are OK. If yes I will go ahead with the merge. Thanks!

**Comment by ryanstewart** [comment]
Strings look good to me. Thanks @peterflynn

**Comment by peterflynn** [comment]
I've rebased atop the latest PR #10884.  Merging into that branch since review here is done...

**Pull request merged**
