### PR TITLE
German Translation: Removing "denglisch" word "updaten"

### PR DESCRIPTION
**Pull request by Milliw**
And replaced it with good old and correct word "aktualisieren"

### CODE REVIEW

**Comment by MarcelGerber** [comment]
@MarcoWilli In order for us to be able to take this change, you need to agree to the [Brackets Contributor License Agreement](http://dev.brackets.io/brackets-contributor-license-agreement.html).

This somehow wonky wording has made me wanna change it, too, but I've not yet gotten around to submitting a PR. This is a welcome change!

**Comment by MarcoWilli** [comment]
I can not submit the license agreement form because it says my email address is not valid! I use mail adress example@mydomain.rocks. Please fixe this -.-

**Comment by MarcelGerber** [comment]
@ryanstewart It looks like the correct-mail-address check doesn't consider the newly added, [generic top level domains](https://www.iana.org/domains/root/db) (like `.rocks`, in this case).

**Comment by abose** [comment]
@prksingh I guess we have to touch the ancient ColdFusion scrolls at the CLA server to make this work?

**Comment by TomMalbran** [comment]
If that is too hard, maybe we could add a cla exception? https://github.com/adobe/brackets/blob/master/tasks/cla-exceptions.json

**Comment by busykai** [comment]
@TomMalbran, the CLA must be signed. `cla-exceptions.json` is not for these cases (you either have to be a bot or still sign a CLA). This is actually urgent enough to fix the mail check.

**Comment by prksingh** [comment]
I have created an issue for this [here](https://github.com/adobe/brackets/issues/11290)

**Comment by abose** [comment]
The CLA check will take a bit of time to resolve, so moving this PR from this release.
For the time being, we will not be able to accept generic TLD mail addresses. 
@MarcoWilli We apologize for this inconvenience.

**Comment by abose** [comment]
Tagging @nethip @ryanstewart for prioritizing this.

**Comment by MarcoWilli** [comment]
Hey guys. Do I need to do something or do we have to wait until the CLA is fixed?

**Comment by MarcelGerber** [comment]
Closing in favor of #11371, which includes these changes.

**Pull request closed without merging**
