### PR TITLE
FR and JP translation fix for Getting Started index.html file

### PR DESCRIPTION
**Pull request by pantkowiak**

### CODE REVIEW

**Comment by redmunds** [comment]
@nethip It looks like this was merged *after* you split off the `release` branch. If you want this in 1.2 it will need to be pulled in.

**Comment by nethip** [comment]
@redmunds Thanks for pointing this out. I will merge this to release branch.

**Comment by peterflynn** [comment]
Luckily there's nothing else on master that's not already on release, so this can be a straightforward merge from master->release without fear of bringing in any other unwanted commits.  If other stuff (not stable enough for 1.2) had landed on master in the meantime, we'd have to `git cherry-pick` this commit instead.

**Comment by nethip** [comment]
@peterflynn I just merged these changes back to release. So this PR should be merged now. Thanks!

**Pull request merged**
