### PR TITLE
Remember last searched phrase & instant search paste fix.

### PR DESCRIPTION
**Pull request by abose**
fix: instant search doesn't work after ctrl+v on textfield
Remember last searched phrase #11735

### CODE REVIEW

**Comment by petetnt** [comment]
Should the `lastQueriedText` persist over Find In Files only or during all the findbar events? (Normal CTRL+F, Search and Replace, Replace in Files...). Consider something like following:

1. Find In Files -> "Hello world"
2. Focus editor 
3. Reopen Find Bar -> it says "Hello world" (expected)
4. Delete "Hello World", replace with "Hot dogs"
5. Focus editor
6. Reopen Find Bar -> it says "Hello world" again
  -> expected: 

a) "Hot dogs" (persisting searches)
b) Nothing? (the current default behavior (without Find in Files/Instant search))

I would be partial for all searches persisting (a))

There's another variation of the previous where it's even more mixed up:

1. Repeat 1-3.
2. Replace with something that exists
3. Focus editor
4. Find the next match with F3
5. Open Find bar -> The last phrase persists
6. Focus editor
7. Open Find bar -> it's "Hello world" again

:+1: for this feature otherwise

**Comment by abose** [comment]
Thanks @petetnt for reviewing. 
I have modified this to save last typed text irrecpective of success of last executed query.

**Comment by petetnt** [comment]
Tested against https://github.com/adobe/brackets/commit/30716f4d765b87617cfc28cf1d0cae4106f0c3ef again and it fixes everything I mentioned in https://github.com/adobe/brackets/pull/11869#issuecomment-152453483 :+1: LGTM as it is.

Here's some food for though: should it remember the position of your search too? Consider something:

1. Make a document

```
bar
foo 1
foo 2
bar
foo 3 
foo 4
```

Search for `foo`, cycle to the third `foo` and focus the editor on the `bar` -> Find-bar closes. Reopen Find bar. Is the expected highlighted one the closest one (the current implementation) or the 3rd one, the one you were in when you focused the editor. I think the latter would make more sense *in most cases* when the last searched phrase persists too.

**Comment by abose** [comment]
I prefer the current implementation, the search progressing closest to the current cursor. That might be individual preference.

**Comment by rroshan1** [comment]
I have verified the changes. Looks good to me.
Point to Note:-
<b>On reopening the "Find in Files" bar, any active selection would be given preference over the last remembered search.</b> :+1: 
Merging the PR.

**Comment by petetnt** [comment]
:cool:

**Comment by abose** [comment]
Thanks all :)

**Pull request merged**
