### PR TITLE
PT-BR translation update

### PR DESCRIPTION
**Pull request by Rynaro**
I've been busy in recently time, but now, I'm ready to return to my "open-source life".
I'm glad to show my recently (emergencial) translation work, for the pt-br.
:smile:

### CODE REVIEW

**Comment by MarcelGerber** [comment]
Some of your lines, namely 669 and 683, miss their trailing comma. That's also why JSHint (and therefore Travis) fails.

**Comment by Rynaro** [comment]
Oh , I had no idea, that I had forgotten the commas . Sorry for my mistake . Now , I've commited my fix . :smiley:

**Comment by MarcelGerber** [comment]
@eliezerb @rodrigost23 Could you maybe take a look at these changes?

**Comment by Rynaro** [comment]
Look at the "Health data", that I've translated as "Relatório de saúde" with intention to make the Brackets more "human".
I open to sugestions.

**Comment by MarcelGerber** [comment]
Due to the lack of feedback, I'm gonna merge this PR as it is.

**Pull request merged**
