### PR TITLE
Added Latvian translation

### PR DESCRIPTION
**Pull request by baibaberzina**
Getting Started section not included yet.

### CODE REVIEW

**Comment by abose** [comment]
@liidzcelim Thank you for contributing to Brackets. Since this is a new language addition, we do not have anyone yet to review this change. If you know anyone who can help with reviewing this change, please feel free to tag them. 
For discussions with the brackets community, please join the [brackets slack channel](https://brackets.slack.com/) by sending a mail to admin@brackets.io with the subject line `slack registration request` specifying the email addresses you would like to register.
[brackets dev google groups link here](https://groups.google.com/forum/#!forum/brackets-dev) .

**Comment by demiters** [comment]
I'm Latvian and able to review the translation. What exactly should I do?

**Comment by abose** [comment]
Hi @demiters , You could go through the changed files and comment if some changes need to be done. If you are ok with the translation, just comment here that the translation is good to go.

**Comment by demiters** [comment]
@abose I've contacted the translator and they're making a few corrections themselves along with implementing my suggestions. Should they submit a new pull request when done?

**Comment by ficristo** [comment]
@demiters @liidzcelim You can just commit on top of this branch. There isn't a need to open a new PR.

**Comment by abose** [comment]
@demiters You could update here with the suggestions so that @liidzcelim can make the changed. 
If there are large number of changes from this PR, please raise a new pull request so that @liidzcelim can review.

**Comment by demiters** [comment]
@abose @liidzcelim I've reviewed the changes, everything looks great. Quality translation :+1:

**Comment by abose** [comment]
Thanks @demiters 
LGTM. merging
Thanks @liidzcelim for contributing this change.

**Pull request merged**
