### PR TITLE
Fix failing tests

### PR DESCRIPTION
**Pull request by marcelgerber**
For #12144 (cc @ficristo)
There's still one FindInFiles test failing, but after looking into it for about 3 hours, I'm giving up on trying to fix that failure.

### CODE REVIEW

**Comment by ficristo** [comment]
Can you give me a bit of background of the FindInFiles issues?

**Comment by MarcelGerber** [comment]
Sure.
* `should disable the Replace button if query is empty`
  As FindBar now remembers the last query, the bar is pre-filled in this test case, whereas it tests the case when the bar is empty. We had the same test fixes for FindReplace in https://github.com/adobe/brackets/pull/12440.
* `should expand/collapse items when clicked`
  I highly doubt this test has ever worked. `#items` is not an actual element to be found in our DOM, but a Mustache section. The new selectors select the actual elements that need to be checked. The `tr` one is that verbose because we don't really have another way to separate `tr.disclosure-triangle` from "normal" `tr` rows.

**Comment by ficristo** [comment]
Thank you.

The SVG test looks fine.
For the first issue of FindInFiles, can you put the function to clean the searchbar in a `beforeEach` function in that `describe` section? If it doesn't cause other issues I would prefer it.
For the second issue I think the point of the test was to check that all lines of a specific list were hidden, with your change you are checking only the first one. I think an option could be to add another class and check for it.

Semi related: when running the FindInFiles test I saw a couple of exception logged in the Developer Tools of test window. Maybe some other timing issue...

**Comment by MarcelGerber** [comment]
I cannot move that expression into the `beforeEach` function because `#find-what` is not part of the DOM at this point, and I also cannot move it into `openSearchBar` because some other tests rely on the bar being pre-populated from a selection (and we can't really distinguish where it comes from).

I've also altered the test so two results are checked, and we now make sure all of the results are hidden or visible, respectively.

**Comment by ficristo** [comment]
> I cannot move that

Thank you to have checked!
If tests pass then LGTM.

**Pull request merged**
