### PR TITLE
Added Bulgarian translation.

### PR DESCRIPTION
**Pull request by lyubomirv**
I have added a Bulgarian translation. The Getting Started project is translated too.

### CODE REVIEW

**Comment by lyubomirv** [comment]
Looks like the test fails for reasons unrelated to my changes.

**Comment by lyubomirv** [comment]
Just adding that I have also tested the translation in Brackets, and everything looks fine! Is there a way to re-run the test, so that they will not fail because of "API rate limit exceeded for XXX" ?

**Comment by abose** [comment]
@lyubomirv  Thank you for contributing to Brackets. Since this is a new language addition, we do not have anyone yet to review this change. If you know anyone who can help with reviewing this change, please feel free to tag them. 
For discussions with the brackets community, please join the [brackets slack channel](https://brackets.slack.com/) by sending a mail to admin@brackets.io with the subject line `slack registration request` specifying the email addresses you would like to register.
[brackets dev google groups link here](https://groups.google.com/forum/#!forum/brackets-dev) .

**Comment by lyubomirv** [comment]
@abose I am afraid I cannot help you find a reviewer but if this means anything, here is my profile on [Transifex](https://www.transifex.com/user/profile/lyubomirv/) which might prove I am a decent translator (I am a reviewer and/or a coordinator for a lot of the projects that I contribute to), so I am pretty confident in the quality of the translation. The whole translation of Brackets has been spell-checked, if that matters too.

**Comment by abose** [comment]
Thanks @lyubomirv For contributing. 
Sorry for the late response.
Merging. as tested.
I am adding you to https://github.com/adobe/brackets/wiki/Translations-community-assistance as our Bulgarian reviewer. Thanks again.

**Comment by lyubomirv** [comment]
@abose Thank you!

**Pull request merged**
