### PR TITLE
bug on find solved

### PR DESCRIPTION
**Pull request by TrocaTudo95**
I solved the issue #13890 . The problem was that when the find bar is opened the function that gets the inital query only was getting the last typed text or a keyword selected and never a word that was searched without typing, now the problem is solved.

### CODE REVIEW

**Comment by TrocaTudo95** [comment]
any feedback please?

**Review by swmitra — APPROVED** [review]
Good work 👍 @TrocaTudo95!

**Comment by swmitra** [comment]
@petetnt @nethip Can you please have a look at this change?

**Comment by nethip** [comment]
Thanks @TrocaTudo95. Is it OK to squash and merge this change?

**Comment by nethip** [comment]
Thanks @TrocaTudo95

**Pull request merged**
