### PR TITLE
update extension manager deps

### PR DESCRIPTION
**Pull request by ingorichter**
This PR will update all the node dependencies of the extension manager. This will hopefully resolve some of the installation issues that we have seen in the past.
All the unit test passed successfully.

### CODE REVIEW

**Comment by ingorichter** [comment]
@MarcelGerber once this got merged, we should update the registry to use a more recent version of the package-validator.

**Comment by lucasecardoso** [comment]
This is not a bug, so I guess it should be closed?

**Comment by ficristo** [comment]
This is a PR, and still valid.
Maybe we can rethink how it is done or update it, but the fact the dependencies should be update is still true.

**Comment by ficristo** [comment]
According to the conversation in https://github.com/adobe/brackets/issues/12898 this seems important.

**Comment by zaggino** [comment]
Closed this in favor of https://github.com/adobe/brackets/pull/12933

**Pull request closed without merging**
