### PR TITLE
Release

### PR DESCRIPTION
**Pull request by rj-adobe**
Fixing the bug DW-4141830

### CODE REVIEW

**Comment by zaggino** [comment]
@abose @nethip what's this? your bot?

**Comment by nethip** [comment]
@zaggino This is coming from our LOC team.

@rj-adobe Could you re-target this PR to master?

**Comment by zaggino** [comment]
@nethip you can actually do that now in github :)

**Comment by nethip** [comment]
@zaggino Oh yeah completely missed the new capability. Thanks for reminding me :smile:

**Comment by zaggino** [comment]
No idea if someone needs to review this, so leaving merge up to you.

**Comment by nethip** [comment]
Yeah  we can merge this.

**Comment by nethip** [comment]
I kind accidentally removed the above comment where I mentioned it is OK to merge. But looks like this PR is going to override strings contributed by the community. Officially, we do translation for `fr` and `jp`.

I will check with @rj-adobe has to why we need to change this string in all the languages.

**Comment by nethip** [comment]
Spoke to @rj-adobe. This can reverted.

**Pull request closed without merging**
