### PR TITLE
Czech translation for v1.4

### PR DESCRIPTION
**Pull request by dvorapa**

### CODE REVIEW

**Comment by MarcelGerber** [comment]
@kvarel Would you mind doing a quick review here?

**Comment by dvorapa** [comment]
Maybe @martinstarman could do a quick review too, because @kvarel looks inactive

**Comment by martinstarman** [comment]
@dvorapa and @kvarel loks good to me :+1:

**Comment by MarcelGerber** [comment]
There've recently been a few late changes to the translation. Could you incorporate these, too? https://github.com/adobe/brackets/compare/867eb6afac5a68b47647af7a213dd1b5c4066789...master#diff-4a1c7e72fe8e80ae96d46411322384c8

**Comment by dvorapa** [comment]
Sure

**Comment by dvorapa** [comment]
Sure, here you are

**Comment by MarcelGerber** [comment]
Thanks! Merging.

**Pull request merged**
