### PR TITLE
French translation: Update uppercases

### PR DESCRIPTION
**Pull request by damienbigot**
Add missing accents on some uppercase letters.

### CODE REVIEW

**Comment by abose** [comment]
ping @swmitra

**Comment by petetnt** [comment]
This one LGTM too :+1:

**Comment by ficristo** [comment]
@damienbigot you need to sign http://dev.brackets.io/brackets-contributor-license-agreement.html.
But usually the French and Japanese translation are maintaned by adobe.
@nethip who can look at this?

**Comment by damienbigot** [comment]
@ficristo I've signed the licence agreement if you want to merge this. Now I know that Adobe maintains French translation.

**Comment by ficristo** [comment]
@damienbigot thank you.
Unfortunately I don't know French, so I cannot evaluate the translation, plus I need some green light from @nethip or someone else at Adobe.
(AFAIK they don't accept PR on those languages :disappointed: )

**Comment by ficristo** [comment]
Ping @swmitra

**Comment by swmitra** [comment]
@ficristo I have forwarded the PR to the corresponding team, once I hear back , will merge this PR.

**Comment by zaggino** [comment]
cc @Tania-Jiacomini @KatarzynaWodzinska

**Comment by swmitra** [comment]
Merging now.

**Pull request merged**
