### PR TITLE
Upgraded npm version to 3.10.10

### PR DESCRIPTION
**Pull request by saurabh95**

### CODE REVIEW

**Review by ficristo — APPROVED** [review]
I thought we were much more behind...
But it doesn't hurt.

**Review by petetnt — APPROVED** [review]
Changeset is okay, but any reason why we are not on `npm@4`?

**Comment by saurabh95** [comment]
I have used the npm version which is shipped with node 6.11.0

**Comment by ficristo** [comment]
We can upgrade to npm 4 in another PR. Merging now.

**Pull request merged**
