### PR TITLE
Remove PanelManager

### PR DESCRIPTION
**Pull request by ficristo**
If I read the git logs correctly, it was deprecated a year ago in favor of WorkspaceManager: I think is time to remove it.
I don't know if there are still extensions using it: there is a way to find it?

In src/utils/Resizer there is an argument called createdByWorkspaceManager, I didn't change it, but I thought it was better to mention it.

### CODE REVIEW

**Comment by Denisov21** [comment]
@ficristo must submitted the contributor license agreement. See http://dev.brackets.io/brackets-contributor-license-agreement.html

**Comment by ficristo** [comment]
I've already done it. Thanks for the reminder :)

**Comment by ficristo** [comment]
Using https://github.com/dangoor/BracketsExtensionGrabber there are still a bit of extensions using PanelManager.
It seems too early to merge this.

**Comment by ficristo** [comment]
I think this should be safe to be merged.

**Review by petetnt — APPROVED** [review]
Looks safe to me

**Comment by ficristo** [comment]
Thanks @petetnt

**Pull request merged**
