### PR TITLE
Add nonexistent translation entries

### PR DESCRIPTION
**Pull request by radhwaw**
Add nonexistent translation entries from strings.js in root directory

### CODE REVIEW

**Comment by radhwaw** [comment]
I have submiited the contributor license agreement

**Comment by radhwaw** [comment]
Please review the translation file

**Review by petetnt — APPROVED** [review]
LGTM codewise

**Comment by radhwaw** [comment]
Hello, has this commit been merged to the adobe:master yet? Or is there anything else that I should be doing? Please advise.

**Comment by ficristo** [comment]
I've checked with https://translate.google.com, LGTM.
@radhwaw thank you.

**Pull request merged**
