### PR TITLE
Created a Guide for Common Linux Issues

### PR DESCRIPTION
**Pull request by NathanJPlummer**
Wrote a guide to fix common issues in Linux, especially Ubuntu.

These problems pop up in the "issues" section every few days despite having several solutions.

Added a link on your main page.  Furthermore moderators can post a link to this guide when someone reports these problems, rather then having to type out the same responses repeatedly.

### CODE REVIEW

**Comment by zaggino** [comment]
@NathanJPlummer great docs indeed. 
Even better place for this would be https://github.com/adobe/brackets/wiki

**Comment by zaggino** [comment]
@NathanJPlummer you need to sign the http://dev.brackets.io/brackets-contributor-license-agreement.html

**Comment by NathanJPlummer** [comment]
@zaggino

Thanks for the feedback.  Signed the form.

I agree the wiki is probably a better location.  From what my research is telling me, I can't do a pull request on a wiki?

I've included the original markdown file I used to build the linked page, but if there's a better solution to this please let me know.  If I see more issues like this pop up I'll attempt to write more documentation in the future.

[Brackets_Linux.zip](https://github.com/adobe/brackets/files/458412/Brackets_Linux.zip)

**Comment by petetnt** [comment]
👍 
Relevant issue I made sometime ago: #12360 

I'd love to see the content in the wiki and I also want the page linked directly to the `README.md` at least as long as generic Linux problems are solved.

**Comment by redmunds** [comment]
Unfortunately, spam bots were polluting the wiki, so currently only committers can update wiki pages.

**Comment by zaggino** [comment]
Merging this then, so @NathanJPlummer can keep it up-to-date on his side until we find a better solution (hostings /docs folder instead of using wiki seems best to me)

**Comment by NathanJPlummer** [comment]
@zaggino 

Works for me.  I'll check issues a couple times a day and add any Linux related issues I see to this.

Thanks!

**Pull request merged**
