### PR TITLE
Adds autofill detail tokens to the autocomplete attribute

### PR DESCRIPTION
**Pull request by Dandandans**
Inspired by [Jason Grigsby](https://cloudfour.com/thinks/autofill-what-web-devs-should-know-but-dont/) and [Christian Heilmann](https://www.smashingmagazine.com/2016/08/contributing-open-source/), this update adds [autofill detail tokens](https://html.spec.whatwg.org/multipage/forms.html#autofill) to the `autocomplete` attribute.

### CODE REVIEW

**Comment by Denisov21** [comment]
Good idea!

**Comment by mcdado** [comment]
Lovely! I was about to make the same PR since Atom uses this list.

But there is one problem, I think: looking at [https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-autocomplete](<input> - HTML | MDN) I see that you did not include "on" and "off".

**Comment by Dandandans** [comment]
@mcdado, yes, it's a nice +1 for both Atom and Brackets. 

I intended to include the `on` and `off` values, but I misread the [WHATWG standard](https://html.spec.whatwg.org/multipage/forms.html#autofill)  for the autofill anchor mantle. 

When the `autocomplete` attribute is wearing the autofill anchor mantle, `on` and `off` shouldn't be combined with autofill detail tokens — e.g. `autocomplete="yes street-address"`. 

The values `on` and `off` are still part of the spec, even though `off`'s usefulness is [debatable](https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion), and should be included as values.

Thanks for helping me rethink this!

**Comment by zaggino** [comment]
:+1:

**Pull request merged**
