### PR TITLE
Fix unittests

### PR DESCRIPTION
**Pull request by sprintr**
Fixes errors in unit tests caused by #11201.

CC: @abose

### CODE REVIEW

**Comment by abose** [comment]
Fixed, merging.

**Comment by sprintr** [comment]
@abose Did all of them pass this time?

**Comment by abose** [comment]
Yes all tests passed. 
If you noticed that `live Preview` tests failed, that intermittently happens, usually some timeout issues, but will pass eventually on rerums.

**Comment by sprintr** [comment]
@abose Only 1 live preview test passed for me at first run.

**Comment by abose** [comment]
yes i too get that at times, but reruns usually does the trick. Might be some timing issue.

**Pull request merged**
