### PR TITLE
CSS: remove unneeded prefixes, add standard properties, remove `px` from 0s

### PR DESCRIPTION
**Pull request by valtlai**
- Add standard `transform`, `filter`, `animation` and `width:
  max-content`
- Remove prefixed `border-radius`, `box-shadow`, `transition`,
  `linear-gradient()`, `box-sizing`, `text-overflow`, `flex-direction`
  and `display: flex`
- Remove prefixed `transform` from standard `@keyframes`
- Remove `px` from zero values

(Replaces #12163)

### CODE REVIEW

**Comment by MarcelGerber** [comment]
Am I right in the assumption that you have had your GitHub name changed? In that case, you need to sign the CLA again (http://dev.brackets.io/brackets-contributor-license-agreement.html).

**Comment by valtlai** [comment]
@MarcelGerber, done.

**Comment by valtlai** [comment]
What is the Chromium version on Linux now? Maybe prefixed `transform` and `animation` can be removed too.

**Comment by MarcelGerber** [comment]
Unfortunately, it's still ~ Chromium 29 on Linux builds.

For some reason, the CLA check still fails, even after re-running the Travis build multiple times. re you sure you have provided the correct username in the form?

**Comment by valtlai** [comment]
@MarcelGerber I think I did.

However, check details contains `"x-ratelimit-limit":"60","x-ratelimit-remaining":"0","x-ratelimit-reset":"1470359670"`

**Comment by ficristo** [comment]
Still LGTM, but I prefer if someone else could do the last check.

**Comment by MarcelGerber** [comment]
I would like to have this briefly tested on Linux as well, at least looking out for obvious regressions.
If no one else offers to take over this task, I can probably revive my Linux Mint VM :)

**Comment by ficristo** [comment]
I gave a try on Ubuntu 16.04 and didn't notice anything obviously wrong.

**Comment by MarcelGerber** [comment]
Going for it in that case. Thank you all!
Merging.

**Pull request merged**
