### PR TITLE
Changed WebPlatform License to MDN License and respective strings

### PR DESCRIPTION
**Pull request by saurabh95**
We still need to get translations for some languages.

### CODE REVIEW

**Comment by ficristo** [comment]
I skimmed through the changes and they seems good.
But I noticed the following things (at the left it is the locale):
- gl: missing urls.js file
- hu: missing urls.js file
- lv: missing urls.js file
- pt-pr: missing entry
- ro: missing urls.js file
- sk: missing urls.js file
- sr: missing urls.js file
- tr: missing entry ABOUT_TEXT_MDN_DOCS (old ABOUT_TEXT_WEB_PLATFORM_DOCS) in strings.js
- uk: missing urls.js file

**Comment by saurabh95** [comment]
The above mentioned locales with no urls.js there is no getting started page defined in sample, so probably this might be the reason of not creating the urls.js

**Comment by ficristo** [comment]
Yeah, what I was trying to say, if you need the text translated everywhere those languages will not be.

**Comment by saurabh95** [comment]
@ficristo I just did replace of Web Platform to MDN, there are some languages which got missed out, since I am not an expert in those languages so I kept them as it is. Once this is merged we can ask Adobe Localization team to verify translations for French and Japanese and the rest of the languages can be verified/corrected by community over time.

**Review by swmitra — APPROVED** [review]

**Pull request merged**
