### PR TITLE
Send the error over to the callback if decompress-zip fails

### PR DESCRIPTION
**Pull request by marcelgerber**
Required for https://github.com/adobe/brackets-registry/pull/69.

### CODE REVIEW

**Comment by ingorichter** [comment]
LGTM. The formatting in the error dialog needs to be updated to provide a better location for the error message.

**Comment by MarcelGerber** [comment]
I don't think there's a need to change the Brackets-internal error message (AFAIK, contrary to the registry, it only ever shows up when there's a real problem with the zip). And changing the server-side error message is part of https://github.com/adobe/brackets-registry/pull/69.

**Comment by ingorichter** [comment]
I meant more the formatting of the error dialog. The error message could be more separated from the remaining text of the dialog box.

**Comment by MarcelGerber** [comment]
So, do you mean the error dialog in Brackets itself or in the registry?

**Comment by ingorichter** [comment]
The error dialog in Brackets

**Comment by ingorichter** [comment]
screenshot 2015-01-14 08 53 32

**Comment by MarcelGerber** [comment]
@ingorichter Would you like to do the change or should I do it?

**Pull request merged**
