### PR TITLE
HTTPS health URL: staging has been upgraded to SSL

### PR DESCRIPTION
**Pull request by abose**
Changing the staging URL to use HTTPS.  @prafulVaishnav

### CODE REVIEW

**Comment by MarcelGerber** [comment]
You should also update the URL in [brackets.config.json](https://github.com/adobe/brackets/blob/master/src/brackets.config.json#L24).

**Comment by abose** [comment]
The file was not changed as brackets.config.json will be picked by installers; so now; the installers will always point to the production server, and all the dev builds will point to the staging server.

**Comment by MarcelGerber** [comment]
The problem here is, though, that `config.json` is automatically updated by `grunt install`, which automatically runs when `npm install` is called.

**Comment by nethip** [comment]
That is what is expected. When `npm install` is run, that is when we are going to update URL to prod. 

Basically we want to update the URL only when `npm install` is run which usually is the case when we create the installer. Of course if someone clones the repo, runs `npm install` and launches brackets from `dist` folder, they will be sending the reports, if opted in, to our prod servers. This is still valid but not a typical case.

**Comment by MarcelGerber** [comment]
Note: That does not only happen when running from `dist`, but also when running from `src`.

Imho, it would make more sense to use the same URL every time, but include a special key whether a build is a dev build or not.

**Comment by nethip** [comment]
I just debugged Brackets by loading index.html from src and I see that the URL is pointing to the `dev` environment. Are you referring to some workflow where this URL is getting overridden by `prod`?

And about `dev` and `prod` environments it is always good to have both the environments. Any changes that need to go into the server first are tested in the `dev` environment and later pushed to `prod`. That way we can be sure that `prod` is always running fine and is not effected with any WIP changes. On the same note we are seeing quite a no of logs for `dev` environment as well.

**Comment by MarcelGerber** [comment]
I meant the setup you have after running `npm install`.

Where this is actually kind-of a problem is in our current [Bracketron](https://github.com/zaggino/brackets-electron) work, where we run `npm install` very often and thus, commit unneeded changes to `config.json`. ([see this](https://github.com/zaggino/brackets-electron/commit/00fdbc81e23400ca5773c72fd864704a1719c5e8#diff-5ca1cd5bde62416d7f8469f969948a94))

**Comment by abose** [comment]
As bracketron is in devolopment stage right now, I think it is ok to push braketron logs to staging instead of production :+1: That would give us separate logs on the braketron effort.

**Comment by MarcelGerber** [comment]
And that's the problem: Currently, they are pushed to production as the URL is changed to `health.brackets.io` by `grunt install` (which runs after `npm install` is called).

**Comment by nethip** [comment]
@MarcelGerber Could you make this change [brackets.config.json](https://github.com/adobe/brackets/blob/master/src/brackets.config.json#L24) in bracketron fork? Let us first figure out the build process in Bracketron and then we can talk about what would be the best way to change `stage` to `prod` URL(may be add additional build grunt step in our installer script?). But for now I would suggest to go with the pushed changes in Brackets.

**Comment by nethip** [comment]
@MarcelGerber Would you have to go through `grunt install` everytime to run bracketron? I believe we run `grunt install` to create `dist` folder and `npm install` to install the dependencies.

**Comment by MarcelGerber** [comment]
No, but as our dependencies change all the time (as it's still work in development), `npm install` (which then calls `grunt install` as a postinstall script) has to be called often as well.
`grunt install` does not build a dist folder, though. It [just runs](https://github.com/adobe/brackets/blob/463547e03d38fe45e752551ac4fef1e3f13b0750/Gruntfile.js#L324) the `write-config` and `less` tasks. The former updates `src/config.json`, the latter creates dist css files (but nothing else!).

What you meant is `grunt build`.

**Pull request merged**
