### PR TITLE
Simplified Chinese: Fix a few translation messages and placeholders

### PR DESCRIPTION
**Pull request by michaeljayt**

### CODE REVIEW

**Comment by peterflynn** [comment]
Changed to more specific title

**Comment by nethip** [comment]
@michaeljayt can you add someone who can do a linguistic review for this change?

**Comment by abose** [comment]
@michaeljayt could you update this PR?

**Comment by michaeljayt** [comment]
Hmm...let me review the latest changes.

**Comment by abose** [comment]
Any review to the changes?

**Comment by michaeljayt** [comment]
OK. now the lastest version here

**Comment by abose** [comment]
Thanks @michaeljayt merged :+1:

**Pull request merged**
